### ISSUE TITLE
mapping already exists in my controller

### ISSUE THREAD

**Issue by kurbhatt** [modelmapper/modelmapper#103]
Hi,

I am getting data from my form and mapping it to my command class but most of field have similar name.
So i have to use explicit mapping using PropertyMap<>.

I have used it and work fine first time but when I am trying or sending second request for processing then it is giving me an error that mapping already exist.

My Controller Code 

@RequestMapping(method= RequestMethod.POST,consumes = "application/json")
    public @ResponseBody
    ResponseEntity<IWebApiResponse> checkOut(@RequestBody CheckOutForm form){
        System.out.println("I  AM Here :; " + form.getAccessionNumber());
        PropertyMap<CheckOutForm,CheckOut> model = new PropertyMap<CheckOutForm,CheckOut>() {
            @Override
            protected void configure() throws IllegalStateException{
                map().setDocumentLibraryId(source.getDocumentLibraryId());
                map().setPatronLibraryId(source.getPatronLibraryId());
                map().setLibraryID(1);
                map().setPatronId(source.getPatronId());
                map().setAccessionNumber(source.getAccessionNumber());
                map().setRemarks(source.getRemarks());
            }
        };
        ModelMapper mapper = Mapper.getInstance();
        mapper.addMappings(model);
        CheckOut command = mapper.map(form, CheckOut.class);
        return ProcessRequest(command);
    }

It is giving me an error

A mapping already exists for com.commands.circulationcommands.CheckOut.setLibraryID()

1 error
    at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:239)
    at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:76)
    at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:110)
    at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:93)

when I put that field in comment in PropertyMap<> then it will give an error for second field and so on.
Any Help on it.

**Comment by aderoks** [comment]
Hi,

I am facing this same problem. Did anyone find a solution or fix this? I am not finding any solution for this on the net.

**Comment by krisdx** [comment]
Here is a work around - http://stackoverflow.com/a/38986521/4672458
