### ISSUE TITLE
Feature request: Map maps to beans and vice-versa

### ISSUE THREAD

**Issue by pvblivs** [modelmapper/modelmapper#12]
I am giving the following test as a simple specification of what I want:

```
@Test(groups = "functional")
public class SimpleMapMapping extends AbstractTest {
  static class Bean {
    String prop1;
    String prop2;
  }

  public void shouldMapBeanToMap() {

    Bean b = new Bean();
    b.prop1 = "valueA";
    b.prop2 = "valueA";
    Map map = modelMapper.map(b, LinkedHashMap.class);

    modelMapper.validate();
    assertEquals(b.prop1, map.get("prop1"));
    assertEquals(b.prop2, map.get("prop2"));
  }

  public void shouldMapMapToBean() {

    Map<String, Object> map = new HashMap<String, Object>();
    map.put("prop1", "valueA");
    map.put("prop2", "valueA");

    Bean b = modelMapper.map(map, Bean.class);

    modelMapper.validate();
    assertEquals(map.get("prop1"), b.prop1);
    assertEquals(map.get("prop2"), b.prop2);
  }
}
```

This is the simple mapping test case. Expected behaviour: Mapping should be strict-only as mapping to a map does not have any properties to match. And if mapping from a map would be loose then mapping back would not yield the original results.
For nested mapping I would expect that the map side of the mapping is fixed. Means: Maps in the bean are treated as values, never as 'maps' in the sense of this feature request.

**Comment by garyschulte** [comment]
I see this is closed, but I am unable to map a pojo to a map as in shouldMapBeanToMap() above.  Is it safe to assume that was never implemented?

**Comment by marklester** [comment]
I  just tried this and it does not populate the map. I think based on the ticket the idea is to have the key be the field and value the value of the field.  Currently this does not work. 
Regards,
