### ISSUE TITLE
generate more "modelmapper" proxy names

### ISSUE THREAD

**Issue by rmannibucau** [modelmapper/modelmapper#125]
hi

When providing a custom PropertyMap then a proxy is generated for source and is used to capture what to do.

The issue is when it is done with container classes these generated classes can be filtered and it can be forbidden to load them from a webapp loader for instance. The solution is trivial: generate org.modelmapper.proxy.<fqn>$$... names insetad of <fsqn>$$... ones.

edit: getDefaultClassLoader() in AbstractClassGenerator should also ensure it uses the classloader the lower between ModelMapper instance and the class to proxy

**Comment by chhsiao90** [comment]
Now we are using ByteBuddy instead of cglib. Feel free to create/reopen issue if there is still concern on the proxied type's name.
