### ISSUE TITLE
Support for mapping interfaces

### ISSUE THREAD

**Issue by jquested** [modelmapper/modelmapper#13]
(Apologies for x-posting this from code.google)

Hi, I'm not sure if this is covered in the documentation anywhere but I have not been able to map from an interface to an object.

```
public class UserAccountMap extends
    PropertyMap<UserModel, UserAccount> {

    @Override
    protected void configure() {
    ...
    }
}
```

In this example, "UserModel" is an interface with relevant getters/setters and UserAccount is a bean. Modelmapper will allow you to create this with no compile errors, but it seems to ignore the "UserModel" interface and look at the underlying class that is implementing the interface.

Alternative to a fix, is there a way around this so I don't have to implement a map for every object that the interface specifies?

**Comment by scottresnik** [comment]
The issue I'm having is that my explicit mappings are not used if they are created with Interfaces as the destination types.

An example is here:
https://github.com/scottresnik/modelmapper-interfaces/tree/master/example.modelmapper

**Comment by chhsiao90** [comment]
The TypeMap inheritance had been release on ModelMapper v1.0.0, please give it a try!
