### ISSUE TITLE
Mapping abstract classes

### ISSUE THREAD

**Issue by tk-codes** [modelmapper/modelmapper#130]
Hello there
I am having a problem with mapping abstract classes.
I have posted the issue on stackoverflow "http://stackoverflow.com/questions/28111875/modelmapper-mapping-abstract-classes-during-runtime".

Does Modelmapper allow mapping abstract classes?

**Comment by chhsiao90** [comment]
Closed by #209

**Comment by chhsiao90** [comment]
The TypeMap inheritance had been release on ModelMapper v1.0.0, please give it a try!
