### ISSUE TITLE
Convert a list of Map to a list of DTO with SourceNameTokenizer is UNDERSCORE

### ISSUE THREAD

**Issue by iguissouma** [modelmapper/modelmapper#133]
I have a class TestDTO with two fields etaTel and etaFax as Strings.
I try to convert a list of Map to a list of TestDTO, I used the source name tokenizer as UNDERSCORE,
when a value in the map is null on the first lines, I got all the list of DTO with a null value.

Here my Test
https://github.com/iguissouma/test-modelmapper/blob/master/test/src/test/java/MappingTest.java

Do you have any idea what's wrong?

Thanks in advance.

**Comment by chhsiao90** [comment]
Fixed by #210
