### ISSUE TITLE
Cannot reuse ModelMapper instance when traversing list with null attributes in some objects

### ISSUE THREAD

**Issue by arathim** [modelmapper/modelmapper#137]
Iam traversing a list of objects, such that an attribute (say iconVal) is null for some entries and the same attribute is not null for other entries. In such case, when I reuse the ModelMapper instance, if I first map an entry with null value for iconVal attribute, the iconVal is not getting mapped, even if it is not null for the other entries.
So Iam re-instantiating ModelMapper for every row. How can I reuse the same ModelMapper instance for traversing such a list?

**Comment by pspi** [comment]
I'm facing this issue as well - took a while to debug. First null value causes subsequent non-null values to be mistakenly read as null.

**Comment by RomanMinenok** [comment]
Wow, guys, this bug is epic. I confirm it exists too. So it's gonna be fixed soon, right?

**Comment by jhalterman** [comment]
@RomanMinenok I'm happy to review any pull requests on this or other issues, but I currently don't have bandwidth to dive into this myself.

**Comment by RomanMinenok** [comment]
@jhalterman Alright, thanks for the feedback!

**Comment by chhsiao90** [comment]
Fixed by #210
