### ISSUE TITLE
Converter not working properly (modelmapper 0.74)

### ISSUE THREAD

**Issue by marhaus** [modelmapper/modelmapper#151]
I have this test case that shows the problem:

``` java
import static org.junit.Assert.assertEquals;

import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.AbstractConverter;
import org.modelmapper.ModelMapper;

public class MappingTest {
    private static final ModelMapper modelMapper = new ModelMapper();

    public static class A {
        private int i;

        public int getI() {
            return i;
        }

        public void setI(int i) {
            this.i = i;
        }

        @Override
        public String toString() {
            return Integer.valueOf(i).toString();
        }
    }

    public static class B {
        private int i;

        // private B() {
        // }

        public B(int i) {
            this.i = i;
        }

        public int getI() {
            return i;
        }

        @Override
        public String toString() {
            return Integer.valueOf(i).toString();
        }
    }

    static class MyMapper extends AbstractConverter<A, B> {
        @Override
        protected B convert(A source) {
            B result = new B(source.getI());

            return result;
        }
    }

    @BeforeClass
    public static void setup() {
        modelMapper.addConverter(new MyMapper());
    }

    @Test
    public void testMapping() {
        A a = new A();
        a.setI(12);

        B b = modelMapper.map(a, B.class);

        assertEquals(a.getI(), b.getI());
    }
}
```

This fails. If I un-comment the private no-argument constructor on the class `B`, then it works.

But since I have a custom `Converter` registered, I should not need that.

I think the problem is with `MappingEngineImpl.typeMap()`; it shouldn't try to create a destination object on its own when there is a `Converter` available.

**Comment by chhsiao90** [comment]
Sorry for the lately reply, I think the behavior is what we expect.

I think convert always happen after construct (via [Provider](http://modelmapper.org/user-manual/providers/) or zero-arg constructor).
Because we are not sure is that converter will construct a object or not.
So it will be safe we construct a destination object before we convert.

Maybe you can try [Provider](http://modelmapper.org/user-manual/providers/)?

**Comment by marhaus** [comment]
If there is a `Converter` available, you will _always_ get an instance from it, according to the Javadoc:
> Converts the MappingContext.getSource() to an instance of MappingContext.getDestinationType().

So `typeMap()` does not need to create its own object if it has a `Converter`, and since it might not even be able to it's a really bad idea to even try. The object would just get discarded anyway, if indeed successfully created.

**Comment by chhsiao90** [comment]
After investigation, I think it makes sense to call the converter.convert immediately if there is a converter defined in a TypeMap. I create a pull request #384 to fix it.
