### ISSUE TITLE
Spring Boot Integration

### ISSUE THREAD

**Issue by jmnarloch** [modelmapper/modelmapper#157]
Hey,

I just wanted to live this note. Since I am a very happy ModelMapper user I have decided to build a seamless integration with Spring Boot: https://github.com/jmnarloch/spring-boot-starter-modelmapper. It allows it to simply drop the extension to Spring Boot app classpath and just inject ModelMapper to any Spring bean.

**Comment by jhalterman** [comment]
Very nice Jakob! I tweeted a link to your blog post.
