### ISSUE TITLE
Unexpected behavior when matching properties with similar names e.g. "id" and "consumerId"

### ISSUE THREAD

**Issue by jdieckmannelm** [modelmapper/modelmapper#166]
**Simplified scenario:**
Source object:

``` javascript
// TokenRequest
{
    consumerId: 123
}
```

results in:

``` javascript
// Token
{
    id: 123,
    consumer: {
        id: 123
    }
}
```

**Full example to reproduce:**
https://github.com/jdieckmannelm/modelmapper-unexpected-behavior

I would not expect the token id to be "123" but null.

Is this behavior by design? If so, is there any way to influence it? Our current solution works perfectly fine with the out-of-the-box-super-magic-auto-mapping, except for this case.

The current workaround is to give the TokenRequest an "id" property or to set the "id" property of the resulting Token to null using an appropriate PropertyMap. We can live with that but maybe we are missing something?

Any help would be appreciated! Thx!

Maybe related to this issue: https://github.com/jhalterman/modelmapper/issues/68

**Comment by mbm56767** [comment]
Facing same issue. when fileds having similar names say id,  getting unexpected values which are supposed to be null

**Comment by chhsiao90** [comment]
Related to #147 too.

**Comment by chhsiao90** [comment]
Hi @jdieckmannelm -

The case you provide is common and make sense.
But currently ModelMapper doesn't support this kind of matching strategy.
Please reference [modelmapper#matching-strategies](http://modelmapper.org/user-manual/configuration/#matching-strategies)

The ModelMapper used Standard as the default matching strategy.
It will only compare the destination field token(not including the parent field) with source field token.
So no matter how deep it is of a destination field, it will only use the field name split into tokens and search the matching field from source fields.

**Comment by chhsiao90** [comment]
Hi @mbm56767 - 

For your case, I suggest you used MatchingStrategies.STRICT as the matching strategy.
And see that will fix for your case. Thanks!

```
mapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
```
