### ISSUE TITLE
Issue in mapping existing nested objects

### ISSUE THREAD

**Issue by kiranreddykasa** [modelmapper/modelmapper#171]
https://groups.google.com/forum/#!msg/modelmapper/WZM6lKUv6QA/on_pqeekBgAJ

**Comment by chhsiao90** [comment]
This is similar to #224 and please reference my [comment](https://github.com/modelmapper/modelmapper/issues/224#issuecomment-300050678).

I will close this issue for now (As there is a similar issue and this issue had been pending for a long time). But please feel free to reopen it 😄

**Comment by chhsiao90** [comment]
Sorry, it seems different to #217 or #224 after investigation...

**Comment by chhsiao90** [comment]
This had been release at modelmapper v1.0.0!
