### ISSUE TITLE
Chaining converters

### ISSUE THREAD

**Issue by kivan-mih** [modelmapper/modelmapper#175]
It could be a good idea to add a possibility for converter chaining. 
For example I have some converter which converts T1 to T2. But for some object I have an Optional<T2> field and I have a converter which converts anything to Optional. What I want is to get a converter chain T1->T2->Optional<T2> using two separate converters.

**Comment by JensRantil** [comment]
I just dug into the code a bit and `ConditionalConverter` _might_ actually support this. Not tested this, though, and someone else probably should chime in if it's possible or not.

**Comment by chhsiao90** [comment]
ConditionalConverter or Converter is not supporting chaining.
But for Optional, I'm working on it to support Optional<A> -> B or A -> Optional<B> at [9584b4b4fef75ed1a29259890fe47c162ee89190|https://github.com/chhsiao90/modelmapper-module-java8/commit/9584b4b4fef75ed1a29259890fe47c162ee89190]
