### ISSUE TITLE
Error when using java 8 streams on PropertyMap

### ISSUE THREAD

**Issue by ratshidaho** [modelmapper/modelmapper#179]
The following test fails with the following messages/errors:

```
org.modelmapper.ConfigurationException: ModelMapper configuration errors:

1) No corresponding mutator was found for  
Test$TestClass.getStrings().
2) No corresponding mutator was found for java.util.Collection.stream().
2 errors

at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:241) at         
org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:229)
at org.modelmapper.PropertyMap.configure(PropertyMap.java:380)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:195)
at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:72)
at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:101)
at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:93)`
```

Code:

```
@org.junit.Test
public void java8StreamsOnModelMapper() {
    new ModelMapper().addMappings(new PropertyMap<TestClass, TestClass>() {
        @Override
        protected void configure() {
            map().getStrings().stream().map(a -> a).collect(Collectors.toList());
        }
    });

}

private class TestClass {
    private List<String> strings = new ArrayList<>();

    List<String> getStrings() {
        return strings;
    }
}`
```

When I remove streams it worked fine.

**Comment by chhsiao90** [comment]
Yeah, the thing accept in PropertyMap.configure are map with getter/setter or fields, plus some converter, provider, condition.
It's not allowed to use anything other than these.

**Comment by krasnopogonnik** [comment]
new ModelMapper().createTypeMap(TestClass.class, TestClass.class).setPostConverter(new Converter<TestClass, TestClass>() {
		      public TestClass convert(MappingContext<TestClass, TestClass> context) {
		    	  context.getDestination().getStrings().addAll(context.getSource().getStrings());
		          return context.getDestination();
		        }
		      });

**Comment by chhsiao90** [comment]
@krasnopogonnik - Sorry, can you describe the problem more? Thanks!

**Comment by krasnopogonnik** [comment]
I have 2 classes generated by wsdl.
`public class ClassA {
	private TypeA propertyA;
	
	public void setPropertyA(TypeA value) {
        this.propertyA = value;
    }
	
	...
	
	private List<TypeB> propertyB;
	
	public List<TypeB> getPropertyB {
		if (propertyB == null) {
            propertyB = new ArrayList<TypeB>();
        }
        return this.propertyB;
	}
}

public class ClassB {
	private TypeA propertyA;
	
	public void setPropertyA(TypeA value) {
        this.propertyA = value;
    }
	
	...
	
	private List<TypeB> propertyB;
	
	public List<TypeB> getPropertyB {
		if (propertyB == null) {
            propertyB = new ArrayList<TypeB>();
        }
        return this.propertyB;
	}
}`
I do not have the right to change anything and If i do:
`ClassA classA = new ClassA();
classA.setPropertyA(valueA);
classA.getPropertyB().addAll(valueB);
ClassB classB = new ClassB();
ModelMapper modelMapper = new ModelMapper();
modelMapper.map(classA, classB);`
in result classB.propertyA = valueA and classB.propertyB = null;

**Comment by chhsiao90** [comment]
It seems that there is not setter for ClassB.propertyB. So you need enable field matching.
Please try
```
modelMapper.getConfiguration()
  .setFieldMatchingEnabled(true)
  .setFieldAccessLevel(AccessLevel.PRIVATE);
```

**Comment by krasnopogonnik** [comment]
In fact, I'm using the Modelmapper with all mappings globally as
Spring Bean. And I can not allow to map all private fields. But I do not doubt that your option is working.
And I apologize for my English.

**Comment by chhsiao90** [comment]
OK, maybe you can try this so that the typeMap could have itself customize config.
```java
Configuration config = modelMapper.getConfiguration().copy();
config.setFieldMatchingEnabled(true)
    .setFieldAccessLevel(Configuration.AccessLevel.PRIVATE);
modelMapper.createTypeMap(ClassA.class, ClassB.class, config);
```

**Comment by krasnopogonnik** [comment]
Thank you. You help me save dozens of lines of code.

**Comment by miloradtrninic** [comment]
How to go around stream and maps? I have the same issue as OP and can't find the solution.
