### ISSUE TITLE
Problems with enum in PropertyMap

### ISSUE THREAD

**Issue by corzar71** [modelmapper/modelmapper#181]
Hello, I'm having issues by using enum methods in **PropertyMap** _configure_.
This is my situation:

> private class TreeNodeMap extends PropertyMap<TbTreeNodes, DTOTree> {
>         protected void configure() {
>             switch (source.getTreeType()) {
>             case ROOT:
>                 //do something
>                 break;
>             case LEAF:
>                 //do something else
>                 break;
>             default:
>                 break;
>             }
>             map().setItemType(source.getTreeType());
>             map().setEntityId(source.getTrnId());
>         }
>     }   

As you can see I need to do some checks depending on Enum values. But using such switch, it raises an error when _modelMapper.addMappings(new TreeNodeMap())_ is invoked.

The error is:

> 1) Cannot map final method java.lang.Enum.ordinal().
> 
> 1 error] with root cause
> org.modelmapper.ConfigurationException: ModelMapper configuration errors:
> 
> 1) Cannot map final method java.lang.Enum.ordinal().
> 
> 1 error
>   at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:241)
>   at org.modelmapper.internal.ExplicitMappingBuilder.visitPropertyMap(ExplicitMappingBuilder.java:229)
>   at org.modelmapper.PropertyMap.configure(PropertyMap.java:380)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)
>   at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:195)
>   at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:72)
>   at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:101)
>   at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:93)

If I comment the switch it works well. It seems that I can't use any Enum method (as _ordinal()_ but _name()_ as well because I did another test by using it).

How can we solve it? I really need to use the switch inside the configure method.
Thanks!

**Comment by chhsiao90** [comment]
Thanks for the report.
The only thing you can do in a ```PropertyMap.configure()``` is map(), skip(), using(), when().
You can't do anything else here, ex: if, switch, for, ...

I don't know about what's your use case, but you might try [Converters](http://modelmapper.org/user-manual/property-mapping/#converters) in PropertyMap.

**Comment by corzar71** [comment]
Hi, thanks. It's what I did at the end.
