### ISSUE TITLE
Lamdas are not supported

### ISSUE THREAD

**Issue by evser** [modelmapper/modelmapper#193]
I must to use anonymous class here:
mapper.addConverter(new org.modelmapper.Converter<Dto, Entity>() { } );

When I use lambda here it simply falls with NPE. It's easy to fix acutally, just use another resolver on your code (in ModelMapper class).

**Comment by lssilva** [comment]
+1

**Comment by ekajani** [comment]
+1

**Comment by chhsiao90** [comment]
@evser - May I ask you which resolver you had used?
I had tried [typetools](https://github.com/jhalterman/typetools) and [SerializedLambda](https://docs.oracle.com/javase/8/docs/api/java/lang/invoke/SerializedLambda.html).
But all failed to resolve the source type of Converter<S, D>.
It can only resolve destination type, but get unknown type for source.
Thanks!

**Comment by evser** [comment]
Unforunately I've resolved only returned type of this lambda (second class in Converter generic expression) using TypeTools.
```
TypeResolver.resolveRawArguments(org.modelmapper.Converter.class, converter.getClass())
```

Result:
**[class net.jodah.typetools.TypeResolver$Unknown, class com.Entity]**

Maybe, it's better to add one more argument for this method?

```
mapper.addConverter(**lambda**, Entity.class)
```

**Comment by chhsiao90** [comment]
Yeah, that seems to be some limitation of resolving raw types of lambda.
I'm working on some lambda friendly api and I will also look into this issue too.
If there is no solution for resolving raw type of lambda, then I think we the only thing we can do is to introduce these kind of methods.

**Comment by evser** [comment]
@chhsiao90 

Maybe the following option is also available:
mapper.<DTO, Entity>addConverter(context -> SOMETHING, DTO.class)

What do you think?

**Comment by jhalterman** [comment]
`ModelMapper.addConverter` is basically an alias for: 

```
TypeMap<Source, Dest> typeMap = modelMapper.createTypeMap(Source.class, Dest.class);
typeMap.setConverter(myConverter);
```

You should be able to use a lambda expression for that second bit, since we already know that we're converting `Source` type to `Dest` type and don't need to extract this info from the lambda:

```
typeMap.setConverter(context -> SOMETHING);
```

**Comment by chhsiao90** [comment]
@jhalterman - Thanks for the answer and the workaround.
@evser - Sorry for the lately reply 😢 .

Here is my thought, I think ```mapper.<DTO, Entity>addConverter(context -> SOMETHING, DTO.class)``` might solve the problem. Because with ```modelMapper.<DTO, Entity>addConverter(context -> SOMETHING)```, ModelMapper will only miss the source generic type. So the only thing we need to do is to let compiler knows what the source type is by explicit define it.

But I will prefer ```modelMapper.addConverter(context -> SOMETHING, DTO.class, Entity.class)```, because it will be a little confused that why only explicitly define source type, no destination type. So if we need explicit define the type, we defined both!

I think @jhalterman 's workaround works nicely too.
If we had applied #214 then the method chain will look great and straightforward.
This will looks like ```modelMapper.typeMap(DTO.class, Entity.class).setConverter(ctx -> sth)```

**Comment by JensRantil** [comment]
Here are two tests. The first one passes, the second one fails:
```java
    @Test
    public void testInferringTypesFromNonLambda() {
        final Converter<String, Integer> converter = new Converter<String, Integer>() {
            public Integer convert(MappingContext<String, Integer> mappingContext) {
                try {
                    return mappingContext.getSource().length();
                } catch (IllegalArgumentException e) {
                    return null;
                }
            }
        };
        testConverterType(converter);
    }

    // Recreates https://github.com/modelmapper/modelmapper/issues/193.
    @Test
    public void testInferringTypesFromLambda() {
        final Converter<String, Integer> converter = mappingContext -> {
            try {
                return mappingContext.getSource().length();
            } catch (IllegalArgumentException e) {
                return null;
            }
        };
        testConverterType(converter);
    }

    private void testConverterType(Converter<String, Integer> converter) {
        final Class<?>[] classes = TypeResolver.resolveArguments(converter.getClass(), Converter.class);
        Assert.assertNotNull(classes);
        Assert.assertEquals(String.class, classes[0]);
        Assert.assertEquals(Integer.class, classes[1]);
    }
```

**Comment by chhsiao90** [comment]
Yeah, we still had problem on resolving argument type of lambda expression.
I think it's a restriction from java. Please reference https://github.com/jhalterman/typetools/issues/40 and https://github.com/jhalterman/typetools/issues/14.
So I don't think there is any solution at this moment...

**Comment by chhsiao90** [comment]
Currently, I think for this issue, we only can do with ```modelMapper.typeMap(Src.class, Dest.class).addConverter(ctx -> ...)```. So I will just close this issue, and feel free to leave comment if you have any solution or idea, thanks!

**Comment by augustojaba** [comment]
This still happens, maybe should be a nice time to re-open?
