### ISSUE TITLE
Support mapAsList, mapAsSet, mapAsXXX

### ISSUE THREAD

**Issue by d0x** [modelmapper/modelmapper#201]
The guys of [orika](https://github.com/orika-mapper/orika) support a convinient way to model List, Sets, ...
It would be handy if modelmapper supports this as well (instead of creating type tokens).

I'm talking about [this api](https://github.com/orika-mapper/orika/blob/master/core/src/main/java/ma/glasnost/orika/MapperFacade.java#L220).

So instead of:

```
List<Integer> numbers = buildIntegers();
Type listType = new TypeToken<List<String>>() {}.getType();
List<String> characters = modelMapper.map(numbers, listType);
```

You would use:

```
List<Integer> numbers = buildIntegers();
List<String> characters = modelMapper.mapAsList(numbers, String.class);
```

which is much more convenient.

What do you think about it and would you accept an PR doing this?

**Comment by d0x** [comment]
Another argument is that the `TypeToken` does not give compiler errors, but `.mapAsList` does.

This example shows that we get a ClassCastException on runtime (which is bad).

```
public class NotTypeSaveTest {

    ModelMapper modelMapper = new ModelMapper();

    @Test
    public void should_not_compile() {
        Type type = new TypeToken<List<String>>() {
        }.getType();

        List<ExampleClass> strings = modelMapper.map(Arrays.asList(1, 2, 3), type);

        // will lead into an ClassCastException
        for (ExampleClass string : strings) {
            System.out.println(string);
        }

        // with .mapToList() it wouldn't
    }

    class ExampleClass {
    }

```

**Comment by chhsiao90** [comment]
Hi,
Thanks for the suggestion! I think the API looks really good,
but currently, I'm not planning to introduce these kind of API.

With JAVA 8 lambda is more and more common,
I think we can solve these kind of mapping by
```java
srcs.stream()
   .map(s -> modelMapper.map(s, Dest.class))
   .collect(Collectors.toXXX())
```

**Comment by chhsiao90** [comment]
I will close this issue at this moment... If anybody had some different idea about this issue, please kindly let me know, thanks!
