### ISSUE TITLE
Invalid assertion inside of model mapper (types for lambda converters not picked up)

### ISSUE THREAD

**Issue by hajdukd** [modelmapper/modelmapper#205]
ModelMapper.java

I think there is an error in assertion line 73 (addConverter)
`Assert.notNull("Must declare source type argument <S> and destination type argument <D> for converter");`

Most likely should be:

`Assert.notNull(typeArguments, "Must declare source type argument <S> and destination type argument <D> for converter");`

Currently it also fails to add converters written as lambdas. 
typeArguments: null   converter: VersionMapConfig$lambda@1394

**Comment by chhsiao90** [comment]
Good catch, thanks!
