### ISSUE TITLE
ModelMapper: Does not map nested collections of List

### ISSUE THREAD

**Issue by ervinfetic** [modelmapper/modelmapper#212]
I have similar example like below:
```javascript
public class FirstObject {
    private List<SecondObject> myListOne;
    ...only getter method...
    ...no setter method for the list due to it is generated from wsdl 
}
public class SecondObject {
    private List<ThirdObject> myListTwo;
    ...only getter method...
    ...no setter method for the list due to it is generated from wsdl
}
public class ThirdObject {
    private String firstName;
    private String lastName;
    ...setters and getters...
}

FirstObject rq = new FirstObject();
...fills some data...

ModelMapper modelMapper = new ModelMapper();
FirstObjectDTO = modelMapper.map(rq, FirstObjectDTO.class);
```

The main issue are setter methods for the lists. If you try with PropertyMap or even with Providers you have to use setter methods and I cannot make them manually because all objects will be regenerated from wsdl each time when I run mvn eclipse:eclipse command.

In case that we have setter methods everything will work properly.

Is there any solution how to make this with Converter??

**Comment by chhsiao90** [comment]
Can you provide more detail about the destination type ```FirstObjectDTO```?
AFAIK, it doesn't matter for source type without setters.

**Comment by ervinfetic** [comment]
@chhsiao90 FirstObjectDTO is totally the same like FirstObject but they are in different packages, something like below:

package: info.myapp.something_v1_1:
- FirstObject.class
- SecondObject.class
- ThirdObject.class

package: info.myapp.something_v1_2:
- FirstObjectDTO.class
- SecondObjectDTO.class
- ThirdObjectDTO.class

Of course both of them have no setters method for the lists.
Only one thing that I did not mention is that **all variables in all classes are protected** but I put in example above public. I made a mistake. For this reason I'm using configuration like below:


modelMapper.getConfiguration().setMethodAccessLevel(AccessLevel.PUBLIC);
modelMapper.getConfiguration().setFieldAccessLevel(AccessLevel.PROTECTED);

**Comment by chhsiao90** [comment]
@ervinfetic - Thanks for the information.
I had tried reproduce the problem you mention according to your information, but still cannot reproduce.
I think different package doesn't matter, so my test won't have different package for different class.
And I had all field protected, all getter public, and no setter.
Please see following code snippet. Is that something I misunderstand about your use case?

```java
import static org.testng.Assert.assertEquals;
import static org.modelmapper.config.Configuration.AccessLevel;

import java.util.Arrays;
import java.util.List;

import org.modelmapper.AbstractTest;
import org.testng.annotations.Test;

@Test
public class DeepListTest extends AbstractTest {
  private int seq = 0;

  static class SrcObj {
    private List<SrcGroup> groups;

    public List<SrcGroup> getGroups() {
      return groups;
    }
  }

  static class SrcGroup {
    private List<SrcItem> items;

    public List<SrcItem> getItems() {
      return items;
    }
  }

  static class SrcItem {
    private String value;

    public String getValue() {
      return value;
    }
  }

  static class DestObj {
    protected List<DestGroup> groups;

    public List<DestGroup> getGroups() {
      return groups;
    }
  }

  static class DestGroup {
    protected List<DestItem> items;

    public List<DestItem> getItems() {
      return items;
    }
  }

  static class DestItem {
    protected String value;

    public String getValue() {
      return value;
    }
  }

  public void shouldMap() {
    modelMapper.getConfiguration().setMethodAccessLevel(AccessLevel.PUBLIC);
    modelMapper.getConfiguration().setFieldAccessLevel(AccessLevel.PROTECTED);

    SrcObj srcObj = new SrcObj();
    srcObj.groups = Arrays.asList(srcGroup(), srcGroup());

    DestObj destObj = modelMapper.map(srcObj, DestObj.class);

    assertEquals(destObj.groups.get(0).items.get(0).value, "foo1");
    assertEquals(destObj.groups.get(0).items.get(1).value, "foo2");
    assertEquals(destObj.groups.get(1).items.get(0).value, "foo3");
    assertEquals(destObj.groups.get(1).items.get(1).value, "foo4");
  }

  private SrcGroup srcGroup() {
    SrcGroup group = new SrcGroup();
    group.items = Arrays.asList(srcItem(), srcItem());
    return group;
  }

  private SrcItem srcItem() {
    SrcItem item = new SrcItem();
    item.value = "foo" + String.valueOf(++seq);
    return item;
  }
}
```

**Comment by chhsiao90** [comment]
Or maybe a minimal reproducer for me that would be better 😄

**Comment by ervinfetic** [comment]
@chhsiao90 You had right my object have a bit different structure. I was wrong in the first example. The new structure is shown below but the other things that I mentions are the same as I described above.

```javascript
public class ParentClassDTO {
    protected FirstObjectDTO firstObject;
    protected NewObjectDTO newObject;
}
public class FirstObjectDTO {
    protected List<FirstObjectDTO.UniqueObjectDTO> myListOne;

    public static class UniqueObjectDTO extends SecondObjectDTO {
        protected String someString;
    }
}
public class SecondObjectDTO {
    protected List<ThirdObjectDTO> myListTwo;
}
public class ThirdObjectDTO {
    protected String firstName;
    protected String lastName;
}
public class NewObjectDTO {
    protected List<BlablaObject> newList;
}
```

```javascript
public class ParentClass {
    protected FirstObject firstObject;
    protected NewObject newObject;
}
public class FirstObject {
    protected List<SecondObject> myListOne;
}
public class SecondObject {
    protected List<ThirdObject> myListTwo
}
public class ThirdObject {
    protected String firstName;
    protected String lastName;
}
public class NewObject {
    protected List<BlablaObject> newList;
}
```
At first I had problem with the "newObject" in parent class. It did not work because class NewObject contains also list without setter method. I found following solution for that case:

```javascript
ModelMapper modelMapper = new ModelMapper();

Converter<NewObject, NewObjectDTO> converter = new Converter<NewObject, NewObjectDTO>() {
    public NewObjectDTO convert(MappingContext<NewObject, NewObjectDTO> context) {

        NewObjectDTO dest = new NewObjectDTO();
        if (context.getSource() != null && context.getSource().getNewList() != null) {

            Type listType = new TypeToken<List<BlablaObject>>() {}.getType();
            List<BlablaObject> items = modelMapper.map(context.getSource().getNewList(), listType);

            dest.getNewList().addAll(items);
            return dest;

        } else {
            return dest;
        }
    }
};
```

**Comment by chhsiao90** [comment]
I think the example you provide still incomplete or wrong.
Can you have a simple demo project or minimal runnable reproducer?
That will help us to figure out what the problem is 😄

**Comment by ervinfetic** [comment]
@chhsiao90  Sorry I was busy last few days. Here you can find just simple example that does not work. In my case example is much more complicated than this one but even this simple for me does not work. Maybe I am doing something in a wrong way. Please take a look.

Here is link of my repo:
https://github.com/ervinfetic/modelmapper-issue-one

I solved this issue with converters like I mentioned above but if I want to use converters for each of my collection then I will need them more then hundred and it does not make sense.

**Comment by chhsiao90** [comment]
No problem, I will take a look. Thanks for giving the reproducible sample code.

**Comment by chhsiao90** [comment]
@ervinfetic - I think I got the point of the issue.
You had mix style of getter and getter/setter of source type and destination type.
So you will fail to map source to destination no matter what if you enable/disable field access.
I will have a minimum demo code for this and think about that if there is any good approach to for this.

**Comment by pachoyan** [comment]
This configuration should work:
```
ModelMapper modelMapper = new ModelMapper();
modelMapper.getConfiguration()
      .setFieldMatchingEnabled(true);
      .setFieldAccessLevel(AccessLevel.PRIVATE);
      ..setSourceNamingConvention(NamingConventions.JAVABEANS_MUTATOR);
```

It enables field mathcing, set the access level as private, and the source naming convention as Mutator to avoid multiple matches with getters.

**Comment by ervinfetic** [comment]
@chhsiao90 I tried that configuration and it works. My issue is solved. Thanks for the help!

Cheers!

**Comment by chhsiao90** [comment]
Nice!
@pachoyan - thanks for your kindly answer, that was really helpful!

**Comment by Endlesslovez** [comment]
> This configuration should work:
> 
> ```
> ModelMapper modelMapper = new ModelMapper();
> modelMapper.getConfiguration()
>       .setFieldMatchingEnabled(true);
>       .setFieldAccessLevel(AccessLevel.PRIVATE);
>       .setSourceNamingConvention(NamingConventions.JAVABEANS_MUTATOR);
> ```
> 
> It enables field mathcing, set the access level as private, and the source naming convention as Mutator to avoid multiple matches with getters.

I have use of you but it create new a error 

1) The destination property vn.isofh.hospital.portal.dto.MenuDTO.setNewsId() matches multiple source property hierarchies:

	vn.isofh.hospital.portal.dao.model.MenuEntity.newsId
	vn.isofh.hospital.portal.dao.model.MenuEntity.news/vn.isofh.hospital.portal.dao.model.NewsEntity.id
	vn.isofh.hospital.portal.dao.model.MenuEntity.news/vn.isofh.hospital.portal.dao.model.NewsEntity.pageId
	vn.isofh.hospital.portal.dao.model.MenuEntity.news/vn.isofh.hospital.portal.dao.model.NewsEntity.menuId

2) The destination property vn.isofh.hospital.portal.dto.MenuDTO.setPageId() matches multiple source property hierarchies:

	vn.isofh.hospital.portal.dao.model.MenuEntity.pageId
	vn.isofh.hospital.portal.dao.model.MenuEntity.page/vn.isofh.hospital.portal.dao.model.PageEntity.id
	vn.isofh.hospital.portal.dao.model.MenuEntity.page/vn.isofh.hospital.portal.dao.model.PageEntity.menuId

**Comment by yadavshivam8091** [comment]
Try     myListOne.add()
After using add you will give all setters.
