### ISSUE TITLE
ModelMapper Roadmap and looking forward to any advise

### ISSUE THREAD

**Issue by chhsiao90** [modelmapper/modelmapper#213]
Hi,

I'm new maintainer of ModelMapper and thanks @jhalterman for giving me the chance.
I'm still junior as an OSS project maintainer and still had a lot of things to learn.
So any advise for me or the project is welcome, I will appreciate it 😄 

Here is the roadmap that I plan to do recently.

#### Short-term
- To have a minor release to address some bugfix #197 #200 #204 #205

#### Mid-term
- To have a major release
  - #210 - Resolved ValueReader handling null value problem
  - #209 - TypeMap inheritance
  - Provide some lambda-friendly interface
- Move to Java 1.6 or Java 1.7

#### Long-term
- #87 - Support for Android
- Address #166 - better handling for name matching (Still have no idea about this, this might be a breaking change...)

**Comment by AlexTrotsenko** [comment]
@chhsiao90 it's good to hear, that this nice project has maintainer and your plan looks great.
 I only want to add, that besides  _dead_ [android-transformer](https://github.com/txusballesteros/android-transformer) lib, I was not able to find anything, which works on Android. So, your plan to support Android eventually looks definitely great! 
Do you already have something in mind? E.g. using ByteBuddy or?
