### ISSUE TITLE
Consider adding public ModelMapper getOrCreate TypeMap capability

### ISSUE THREAD

**Issue by jhalterman** [modelmapper/modelmapper#214]
I've thought about this numerous times, but one of the drawbacks of the current API is it forces you to think about whether you're getting or creating a TypeMap:

```
modelMapper.createTypeMap
modelMapper.getTypeMap
```

Internally though, we safely do a getOrCreate to lookup a TypeMap if it exists, else create it. It would be convenient, and might make sense, to allow users to do the same thing:

```
TypeMap<Foo, Bar> typeMap = modelMapper.typeMap(Foo.class, Bar.class);
```

or

```
TypeMap<Foo, Bar> typeMap = modelMapper.typeMapFor(Foo.class, Bar.class);
```

This might relieve the need for separate `createTypeMap` and `getTypeMap` methods altogether.

Any thoughts?

**Comment by chhsiao90** [comment]
I'm not sure which is your intension about the method
- replacement of ```createTypeMap``` and ```getTypeMap```
- additional methods other than ```createTypeMap``` and ```getTypeMap```

I think you might mean the first one as you had point out
> This might relieve the need for separate createTypeMap and getTypeMap methods altogether

I think it will be good api and really convenient that we only need to call ```typeMap``` or ```typeMapFor``` to create or get TypeMap.
But as a replacement of ```createTypeMap``` and ```getTypeMap```, I think it need to have all functionality of ```createTypeMap``` and ```getTypeMap```. 

So there will be a little confused in some case,
like when we call ```typeMapFor(Source.class, Destination.class, config)```,
but there is already a TypeMap<Source, Destination> in store with different config.

**Comment by jhalterman** [comment]
I would think of `typeMap(Class, Class)` as an additional method for `createTypeMap(Class, Class)` and `getTypeMap(Class, Class)`. We can probably also add `typeMap(Class, Class, String)`.
