### ISSUE TITLE
Size of model mapper JAR in 0.7.8 vs 0.7.5

### ISSUE THREAD

**Issue by user140547** [modelmapper/modelmapper#219]
When downloading the ModelMapper JAR from http://modelmapper.org/downloads/ I get a JAR which is about 500 KB. (0.7.5)

However, 0.7.8,  has almost 2,5 MB. See https://mvnrepository.com/artifact/org.modelmapper/modelmapper/0.7.8 
It seems that in latter version (0.7.8), there are some org.apache.tools packages which are not included in the "regular" download. Are those packages really needed?

**Comment by chhsiao90** [comment]
Thanks for the report, good catch!
I didn't notice that the jar size had changed.
And it seems start from v0.7.7, I will take a look!

**Comment by chhsiao90** [comment]
It's https://github.com/modelmapper/modelmapper/commit/5933cf1215d5ac35cdce6ec83edf3787140ebde7 to introduce the dependency and might related to [cglib/cglib/pull/87](https://github.com/cglib/cglib/pull/87) .
I think we can exclude the ant dependency in our pom.xml.
Will fix in next release.

And thanks for your report!

**Comment by chhsiao90** [comment]
This had been release by v1.0.0!
