### ISSUE TITLE
Use converter to map the main object

### ISSUE THREAD

**Issue by corzar71** [modelmapper/modelmapper#231]
Hello, I've an issue mapping a particular structure.
Basically my goal is to obtain a flat object from a hierarchical one. The problem is that I can't use a direct mapping because there are some condition to be evaluated and then I'm forced to use a Converter. Unfortunately Converters can be used only to map properties and not to map the whole object. How can I obtain the whole object?
Example:

```
class TbA {
      List<TbB> tbBs
}

Class TbADTO {
     ....some properties of TbB
}

```
Can you help me?

**Comment by corzar71** [comment]
Further info. If I map in this way

```
	private class MyMap extends PropertyMap<TbA, TbADTO> {
		protected void configure() {
			using(myConverter).map(source.getTBBs());
                        .
                        .
                        .
		}
	}
```
I have the following errors:

> 1) A mapping is missing a required destination member.
> 
> 2) Cannot map final method org.modelmapper.PropertyMap.using().
> 
> 3) Invalid destination method org.modelmapper.PropertyMap.using(). Ensure that method has one parameter and returns void.
> 
> 4) A mapping is missing a required destination member.

if I map in this way:
`			using(myConverter).map(source.getTBBs(), destination);
`
I have the following error

> 1) A mapping is missing a required destination member.

**Comment by corzar71** [comment]
I solved by using a workaround but it's really ugly.
I created a circular reference in the TbA class
```
class TbA {
      TbA tbA;
      List<TbB> tbBs
}
```
and I used the converter in this way:

> using(myConverter).map(source.getTBBs()).setTbA(null);

It works but as I said it's very ugly. I hope you can give me the right tip to solve it by using the initial structure of TbA.

**Comment by chhsiao90** [comment]
@corzar71 - Thanks for the report. I think the problem you want to ask is that you want to define a PropertyMap to mapping a field of destination directly, but ModelMapper was not allowed you to do this. Am I correct? I will take a look that if we can support for this.

**Comment by chhsiao90** [comment]
I'm not fully know about your use case,
I will give you my suggestion base on what I know about your case.

I suggest that you should forget about mapping, just use converter.
```java
modelMapper.addConverter(new Converter<TbA, TbADTO>() {
   ...
});
```

Or maybe you can try using converter for each property of TbADTO
```java
modelMapper.addMappings(new PropertyMap<TbA, TbADTO>() {
    public void configure() {
         using(converter1).map(source.getTbBs()).setPropertyA(null);
         using(converter2).map(source.getTbBs()).setPropertyB(null);
         using(converter3).map(source.getTbBs()).setPropertyC(null);
    }
});
```

**Comment by corzar71** [comment]
Hi @chhsiao90 I answer you below:

>  I think the problem you want to ask is that you want to define a PropertyMap to mapping a field of destination directly, but ModelMapper was not allowed you to do this. Am I correct?

yes. Actually to map the destination directly, not really its field.

> Or maybe you can try using converter for each property of TbADTO

I thought to that solution as well but, first of all I should create many similar converters, and it's not really the best, and anyway, if I use many converters, I'm not able to distinguish which collection object I have to assign to each property. Instead If I do everything in the same context I'm able.

Many thanks for your support.

**Comment by chhsiao90** [comment]
After some investigation, I think it's dangerous to support mapping to destination directly and it violates the design of ModelMapper, because ModelMapper always mappings based on destination's property.

So I think the ways you can fix it are addressed at my previous [comment](https://github.com/modelmapper/modelmapper/issues/231#issuecomment-301421745) by just using ```modelMapper,addConverter``` or defines mappings for each property of destination.

**Comment by corzar71** [comment]
Ok, I'll try to implement the first suggestion because the second cannot fit my needs.
Thanks for support
KR

**Comment by chhsiao90** [comment]
@corzar71 - Thanks for your understanding :-)

**Comment by corzar71** [comment]
Hi @chhsiao90 I used your suggestion
```
modelMapper.addConverter(new Converter<TbA, TbADTO>() {
   ...
});
```
and it worked like a charme! Actually it was just what I needed but I didn't know I could use a converter directly in the model mapper by  the`addConverter` method. Maybe it would be better to add it in the documentation.
Many thanks again for your support!
