### ISSUE TITLE
Field Conversion Error

### ISSUE THREAD

**Issue by jungrammer** [modelmapper/modelmapper#234]
So have following scenario:

Below are two classes to convert.

1. 
`
        @Data
        class A {
                private String testGooGo;
        }
`

2. 
`
        @Data
        class B {
                private String testGooGo;
        }
`

If you run the following code in both classes,
Conversion does not work normally.

`
        ModelMapper modelMapper = new ModelMapper();
        
        A a = new A();
        a.setTestGooGo("abcd");

        B result = modelMapper.map(a, B.class);
`

Can you solve this problem?
Junhoi

**Comment by chhsiao90** [comment]
Thanks for the report.
I think this was really a bug that ModelMapper didn't think the source's testGooGo and the destination's testGooGo match.

The workaround before I fixed this please use PropertyMap if you are urgent with this case.
```java
modelMapper.addMappings(new PropertyMap<A, B> {
  public void configure() {
    map().setTestGooGo(source.getTestGooGo());
  }
});
```

**Comment by chhsiao90** [comment]
@jungrammer - This had been release at modelmapper v1.0.0!
