### ISSUE TITLE
java.util.Map properties not listed in the propertyMapping array

### ISSUE THREAD

**Issue by lsantos** [modelmapper/modelmapper#240]
I am using the modelmapper jooq extension, and I can't get hstore columns to get mapped to a java bean.

By debugging the code, I see the record object returned by my dslContext fetches the hstore column properly, I also have a HstoreBinding class that is responsible to implement the binding to java.util.Map<String, String> field. In the return of the method typeMap.getMappings() I do not see the attributes that have the mapping from hstore to java.util.Map.

I was wondering whether I have to add any configuration to make this mapping happen or model mapper jooq extension can figure this out by itself.

**Comment by chhsiao90** [comment]
@lsantos - Thanks for the report. I would like to know which modelmapper version you used! We had a broken change of ValueReader at v1.0.0. And I want to make sure that the problem is related to the broken change or not. Thanks.

**Comment by lsantos** [comment]
@chhsiao90 - not a problem. I am using version 0.7.6.

**Comment by lsantos** [comment]
@chhsiao90 I did some more debugging yesterday, in the version that I am using the RecordValueReader is doing its job, the accessors are getting populated.

I am sharing our project model mapper configuration:

 ModelMapper modelMapper = new ModelMapper();
        modelMapper.getConfiguration().addValueReader(new RecordValueReader());
        modelMapper.getConfiguration().setSourceNameTokenizer(UNDERSCORE);
        modelMapper.getConfiguration().setFieldMatchingEnabled(true);
        modelMapper.getConfiguration().setFieldAccessLevel(PRIVATE);

The 2 fields that are not being mapped all follow the underscore database column name, camel case java property naming convention, nothing out of ordinary.

I have a hunch that the MatchingStrategy class for some weird condition is not being able to match their names.

**Comment by chhsiao90** [comment]
Can you provide what's the property name of the source and what's the property name of the destination? Thanks

**Comment by lsantos** [comment]
Sure, it is merchant_details for the source, and merchantDetails for the destination.

When debugging yesterday, I noticed that the PropertyNameInfo object that the class StandardMatchingStrategy uses had the value of the java.util.Map key in its source properties field, something like this: 

PropertyNameInfoImpl[sourceProperties=[merchant_details, MY_MAP_KEY], destinationProperties=[MerchantProfileDTO.merchantDetails]]

Which makes the match logic fail.

**Comment by chhsiao90** [comment]
Where's the MY_MAP_KEY comes from? That's really weird! Could you provide more detail or a minimum reproducer? Thanks!

**Comment by lsantos** [comment]
It's actually the keys that we have in the postgres hstore db column, e.g:

PropertyNameInfoImpl[sourceProperties=[merchant_details, SERVICE_PROVIDER_MONERIS_STOREID], destinationProperties=[MerchantProfileDTO.merchantDetails]]

Somehow, the db column value gets populated in the sourceProperties class attribute.

I will try to isolate the issue in a small project.

**Comment by lsantos** [comment]
Another weird thing that I am seeing is that classes that belong to the java sdk are being used to find matches against my java DTOs.

**Comment by lsantos** [comment]
Hi @chhsiao90,

You can close this issue as issue https://github.com/modelmapper/modelmapper/issues/118 fixed my problem.

**Comment by chhsiao90** [comment]
Nice!

**Comment by kranthi34** [comment]
Any one please provide some example configuration and testcase please as am facing same issu

**Comment by kranthi34** [comment]
Modelmapper configuration.

@Bean
	public ModelMapper modelMapper() {
		ModelMapper mapper = new ModelMapper();

		mapper.getConfiguration().addValueReader(new RecordValueReader()).setSkipNullEnabled(true)
				.setPropertyCondition(Conditions.isNotNull());
		return mapper;
	}

and my custom mapper class is as follows:

package com.centerpoint.ars.payments;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;

import org.modelmapper.Conditions;
import org.modelmapper.Converter;
import org.modelmapper.ModelMapper;
import org.modelmapper.TypeMap;
import org.modelmapper.jooq.RecordValueReader;
import org.springframework.stereotype.Component;

import com.centerpoint.ars.customutils.ContextUtils;
import com.centerpoint.ars.generated.model.enums.Recordstatus;
import com.centerpoint.ars.generated.model.tables.pojos.Paymentsettlement;
import com.centerpoint.ars.generated.model.tables.records.PaymentsettlementRecord;

@Component
public class PaymentSettlementMapper {

	private ModelMapper mapper = new ModelMapper();

	public ModelMapper getMapper() {
		 mapper.getConfiguration().addValueReader(new RecordValueReader());
		 mapper.getConfiguration().setSkipNullEnabled(true);
		 mapper.getConfiguration().setPropertyCondition(Conditions.isNotNull());
		final Converter<LocalDate, LocalDate> DATE_TO_LOCAL_DATE_CONVERTER = mappingContext -> {
			return mappingContext.getSource();
		};
		final Converter<LocalDate, LocalDate> LOCAL_DATE_TO_DATE_CONVERTER = mappingContext -> {
			return mappingContext.getSource();
		};

		TypeMap<PaymentSettlementDTO, PaymentsettlementRecord> paymentSettlementMapping = mapper
				.getTypeMap(PaymentSettlementDTO.class, PaymentsettlementRecord.class);
		if (paymentSettlementMapping == null) {
			paymentSettlementMapping = mapper.createTypeMap(PaymentSettlementDTO.class, PaymentsettlementRecord.class);
			paymentSettlementMapping.addMappings(mapping -> mapping.using(LOCAL_DATE_TO_DATE_CONVERTER));
		}
		TypeMap<PaymentsettlementRecord, PaymentSettlementDTO> paymentSettlementRecordMapping = mapper
				.getTypeMap(PaymentsettlementRecord.class, PaymentSettlementDTO.class);
		if (paymentSettlementRecordMapping == null) {
			paymentSettlementRecordMapping = mapper.createTypeMap(PaymentsettlementRecord.class,
					PaymentSettlementDTO.class);
			paymentSettlementRecordMapping.addMappings(mapping -> mapping.using(DATE_TO_LOCAL_DATE_CONVERTER));
		}

		TypeMap<HashMap, PaymentsettlementRecord> paymentSettlementMapMapping = mapper.getTypeMap(HashMap.class,
				PaymentsettlementRecord.class);
		if (paymentSettlementMapMapping == null) {
			paymentSettlementMapMapping = mapper.createTypeMap(HashMap.class, PaymentsettlementRecord.class);
			paymentSettlementMapMapping.addMappings(mapping -> mapping.using(LOCAL_DATE_TO_DATE_CONVERTER));
		}
		return mapper;
	}

	public Paymentsettlement mapToPojoCreate(PaymentSettlementDTO paymentSettlementDto) {
			Paymentsettlement paymentSettlement = mapper.map(paymentSettlementDto, Paymentsettlement.class);
			paymentSettlement.setBalanceamount(paymentSettlementDto.getAmount());
			paymentSettlement.setBranchid(ContextUtils.getContext().getLocationId());
			paymentSettlement.setCreatedip(ContextUtils.getContext().getIpAddress());
			paymentSettlement.setCreatedby(ContextUtils.getContext().getName());
			paymentSettlement.setCreateddate(OffsetDateTime.now());
			paymentSettlement.setStatus(Recordstatus.ACTIVE);
			paymentSettlement.setCompanyid(paymentSettlementDto.getCompanyid());
			return paymentSettlement;
	}

	public PaymentsettlementRecord mapToPojoToUpdate(Map<String, Object> paymentDto, PaymentsettlementRecord paymentRecord) {
		getMapper().map(paymentDto, paymentRecord);
		paymentRecord.setUpdateddate(OffsetDateTime.now());
		paymentRecord.setUpdatedby(ContextUtils.getContext().getName());
		paymentRecord.setUpdatedip(ContextUtils.getContext().getIpAddress());
		return paymentRecord;
	}
}

and i want to map

mapper.map(Hashmap.class, jooqrecord.class)

**Comment by kranthi34** [comment]
but some fields are not mapping even though the field names are same in both java.util.map and record 
ex:- balanceamount in both map and record column name

**Comment by kranthi34** [comment]
@chhsiao90, @lsantos  please could you help me please!
