### ISSUE TITLE
Assigning converters to collection entries

### ISSUE THREAD

**Issue by sadimusi** [modelmapper/modelmapper#248]
I'm trying to find a way to assign a `Converter`, which converts elements of one `Collection` to elements of another, to a specific property. 

Given the following minimal data objects:
```java
class A {
  private List<String> lowerCaseList;
  private List<String> someOtherList;
}

class B {
  private List<String> upperCaseList;
  private List<String> someOtherList;
}
```
And the converter from your documentation:
```java
Converter<String, String> toUppercase =
    ctx -> ctx.getSource() == null ? null : ctx.getSource().toUppercase();
```

How can I get all the items in `A.lowerCaseList` to be converted by `toUppercase`, while the ones in `someOtherList` remain unchanged? Surely there needs to be a better solution than to write a `Converter<List<String>, List<String>>`.

**Comment by chhsiao90** [comment]
@sadimusi - Thanks for the report. It looks like ModelMapper is not covered for your case... Unless you used an ugly ```Converter<List<String>, List<String>>```.
Sadly, I have no idea about how to improve it at this moment...
If you had any idea for how we can improve please let me know. And feel free to keep this PR opened, hope that somebody would some idea about solve this issue!

**Comment by sadimusi** [comment]
Well, there are a few options:

The first thing I tried, but did not work as expected, looked like this:
```java
mapper.typeMap(A.class, B.class)
    .addMappings(mapper -> mapper.using(toUppercase)
                                 .map(A::getLowerCaseList, B::setUpperCaseList);
```
ModelMapper could detect that the provided `Converter` in this case does not map the top-level objects, but the items they contain.

Another approach, which requires more explicit declaration by the application, would be to provide some static function which converts a simple `Converter<A, B>` to a collection converter `Converter<Collection<A>, ? extends Collection<B>>`. It might be a little tricky to get this to work with all possible types of `Collection`, a simpler version could just offer different functions for the different types.
```java
mapper.typeMap(A.class, B.class)
    .addMappings(mapper -> mapper.using(collectionConverter(toUppercase))
                                 .map(A::getLowerCaseList, B::setUpperCaseList);
```

**Comment by chhsiao90** [comment]
@sadimusi - The second one approach make sense to me, and the API looks great! So we will have an util class Converters that provide some converter decorators. That is really GOOD idea. Are you interested at having a PR for this?

**Comment by sadimusi** [comment]
Unfortunately I won't have time to actively work on open-source projects for the rest of the month, but after that I might be able to take this on.
