### ISSUE TITLE
Skipping Properties documentation error

### ISSUE THREAD

**Issue by palmeirense1099** [modelmapper/modelmapper#259]
The 'Skipping Properties' documentation says the "null value is unused". But that is not the case. This assumes that you are mapping from a source object with values to a new destination object without values (nulls). But what if you are mapping between two objects with values? In that case it DOES use the null and wipes out the destination value.

The way I found around this was to use the following, but it should be documented correctly:

skip().setField1(source.getField1());
//vs.
skip().setField1(null); //always sets to null

Current documentation: "Note: Since the setName method is skipped the null value is unused."

**Comment by chhsiao90** [comment]
AFAIK, ```skip().setField1(source.getField1())``` is same as ```skip().setField1(null)```
The value on the destination's setter doesn't matter when we want to skip a destination property.
We always need pass a value as a parameter when we call the destination's setter. So that's why ```null``` is here.
