### ISSUE TITLE
Map own java class to and from enum issue

### ISSUE THREAD

**Issue by SomeDude1234** [modelmapper/modelmapper#262]
Hi,

I'm having an issue with the following:
We have an own java class and we have to map several enums to and from this class.

For a boolean I'm using the abstractconverter without problem, but when I use Enum the converter is not used (I think he keeps using the default enumconverter from modelmapper).
Only thing that works is for each enum, create a converter but that's a hell of a job.
How can I create 1 converter to convert from Enums -> myClass and 1 that does the myClass -> Enum ?

**Comment by chhsiao90** [comment]
Can you provide your source code or minimum reproducer that the custom enum->myClass not working? AFAIK, custom converter always have high priority than predefined converter. Thanks!

**Comment by SomeDude1234** [comment]
public class EnumToMyObjectConverter extends AbstractConverter<Enum, String> {

    @Override
    protected String convert(Enum aEnum) {
        if(aEnum != null) {
            return aEnum.name();
        }
        return "";
    }
}

I add converters:
modelMapper.addConverter(new EnumToMyObjectConverter());

Enum sample
public enum Day {
    SUNDAY, MONDAY, TUESDAY, WEDNESDAY,
    THURSDAY, FRIDAY, SATURDAY
}


MatchingStrategies is STANDARD

**Comment by chhsiao90** [comment]
Hi @SomeDude1234 
You should try ```AbstractConverter<Day, String>``` instead of ```AbstractConverter<Enum, String>```, because ModelMapper will select a converter or type map by ```<Day, String>``` instead of ```<Enum, String>```.

**Comment by SomeDude1234** [comment]
@chhsiao90 
That's my problem: I have multiple enum types and I don't want to make a converter for each enum!
I see there is a default enumconverter so I believe it should be possible to override this one somehow

**Comment by chhsiao90** [comment]
@SomeDude1234 
Please try adding your own ConditionConverter to ModelMapper's own converter store.

```java
    modelMapper.getConfiguration().getConverters().add(0, new ConditionalConverter<Enum<?>,String>() {
      public MatchResult match(Class<?> sourceType, Class<?> destinationType) {
        if (sourceType.isAssignableFrom(Enum.class) && destinationType.isAssignableFrom(String.class)) {
          return MatchResult.FULL;
        }
        return MatchResult.NONE;
      }

      public String convert(MappingContext<Enum<?>, String> context) {
        return context.getSource() != null ? context.getSource().name() : "";
      }
    });
```

**Comment by SomeDude1234** [comment]
@chhsiao90 
Works better but sourceType.isAssignableFrom(Enum.class) is never true (cause it's my enum that is passed, not the enum). Quick fix is sourceType.getGenericSuperclass().getTypeName().startsWith("java.lang.Enum")  but that's a bit dirty imo :)
