### ISSUE TITLE
How to convert list of enums to int array? 

### ISSUE THREAD

**Issue by mrshawn191** [modelmapper/modelmapper#276]
How to convert list of enums to int array? 

Do I need a converter, how would that look? 

Thanks in advance.

**Comment by kobbikobb** [comment]
private enum Color {
        GREEN(0),
        BLUE(1),
        BLACK(2);

        private final int value;

        Color(int value) {
            this.value = value;
        }

        public int getValue() {
            return value;
        }
    }

    @Test
    public void shouldMapEnumArrayToIntArray() {
        ModelMapper modelMapper = new ModelMapper();
        Converter<Color, Integer> toInteger = new AbstractConverter<Color, Integer>() {
            @Override
            protected Integer convert(Color color) {
                return color.getValue();
            }
        };
        modelMapper.addConverter(toInteger);
        List<Color> colors = Lists.newArrayList(
                Color.GREEN,
                Color.BLACK,
                Color.BLUE,
                Color.GREEN
        );
        
        Integer[] result = modelMapper.map(colors, Integer[].class);

        Integer[]  expectedResult = new Integer[] {0, 2, 1, 0};
        assertThat(expectedResult, Matchers.is(result));
    }

**Comment by mrshawn191** [comment]
thank you for the help

**Comment by kobbikobb** [comment]
Np
