### ISSUE TITLE
Best practise of using ModelMapper

### ISSUE THREAD

**Issue by wudong** [modelmapper/modelmapper#277]
So we have many classes to map; they scatter across many packages in their own domain.

I want to use ModelMapper reduce code clustering to but not sure what's the best practise of using it. My main question so far is:

Should a single instance of ModelMapper exists in the whole application, which will then contain many mapping definition from different places? 

Or is it ok to have a ModelMapper created for each domain? and let it maintain the mapping of the domain only.

The latter will be much cleaner and less error prone,  but I'm not sure the implication. Is ModelMapper light weight enough for this usage?

**Comment by chhsiao90** [comment]
I think it's okay to maintain multiple ModelMapper instances.

**Comment by jhalterman** [comment]
Agree - nothing wrong with having multiple ModelMapper instances. Only thing to note is each instance will maintain its own TypeMaps, which are the definition of how one type maps to another. If each of your ModelMapper instances map the same types, then there's probably no point to having multiple instances. If you need to vary the configuration for mapping between two types, you can also use a named type map: `ModelMapper.typeMap(Source.class, Destination.class, "someName")` to distinguish different TypeMaps for different purposes.
