### ISSUE TITLE
merge functionality - feature request

### ISSUE THREAD

**Issue by fssrepository** [modelmapper/modelmapper#280]
ModelMapper is making a good job on transformation between dto and entity.

Can i use ModelMapper for merge?

We have a list of dto objects, which has unique string based identifiers, entity also has that, but the dtos 
do not contain the primary key of the table naturally.

I would like to update the entity from the updated dto. It can be standardized also, instead of making similar boilerplate codes.

Any idea, how it can be solved effectively with ModelMapper?

**Comment by chhsiao90** [comment]
I think we can merge properties into one entity/dto, but it still had some restriction.
Maybe you can try this
```
modelMapper.map(yourDto, yourEntity);
```
You might also need to set PropertyCondition to prevent the entity field to be overwrite with null value
```
modelMapper.typeMap(Dto.class, Entity.class).setPropertyCondition(Conditions.IS_NOT_NULL)
```
