### ISSUE TITLE
OSGi Import-Package list is wrong in the dependency-reduced pom

### ISSUE THREAD

**Issue by mdzhigarov** [modelmapper/modelmapper#284]
This is the complete list of import packages in the jar that is generated from the dependency-reduced pom:

```
Import-Package: javax.xml.datatype,net.jodah.typetools;version="[1.0,2
 )",org.modelmapper.builder,org.modelmapper.config,org.objectweb.asm;v
 ersion="[5.1,6)",org.objectweb.asm.tree;version="[5.1,6)",org.objenes
 is;version="[2.1,3)"
```

As you can see, asm and objenesis are part of the required packages.
But in fact they are shaded into the modelmapper jar so they must be excluded

**Comment by mdzhigarov** [comment]
Additionally, it seems that the Shade plugin is embedding classes from asm, objenesis and typetools into some internal modelmapper package, i.e:
org.modelmapper.internal.typetools instead of net.jodah.typetools

Instantiating the ModelMapper then fails with java.lang.NoClassDefFoundError: net/jodah/typetools/TypeResolver, since such class is not available on the runtime since it was shaded under a wrong path

**Comment by jhalterman** [comment]
Are you up for sending a PR for this?

**Comment by mdzhigarov** [comment]
Sure, I will see what I can do in the next days
