### ISSUE TITLE
Detection of "circular dependencies" causes to return empty/null objects

### ISSUE THREAD

**Issue by almoghzn** [modelmapper/modelmapper#297]
I have the following data structure which I want to map (in parenthesis is the instance id):

Show (11)
   Screen (21)
      Source (31)
         name:String = "a" (311)
      Source (32)
         name:String = "b" (312)
Show (12)
   Screen (21)
      Source (31)
         name:String = "a" (311)
      Source (32)
         name:String = "b" (312)

Explanation:
I want to map:
List of Show
Which each Show contains Screen
Which each Screen contains List of Source

Note:
The two shows are different instances!
But the Screen which exists at the first Show and at the second Show is the same instance.
According to that, the Sources instance are the same instances for the first Show and the second.

Also,
I have custom converter for object type of Source!

Now,
When I tried to map this data structure I get the following:
Show (11)
   Screen (21)
      Source (31)
         name:String = "a" (311)
      Source (32)
         name:String = "b" (312)
Show (12)
   Screen (21)
      Source (31)
         name:String = null
      Source (32)
         name:String = null
i.e. the second list of Source will return with all members assigned to null!

This happens because:
There is logic to detect circular mapping.
Therefore each map saved into MappingContextImpl.sourceToDestination
Once the MappingEngineImpl tries to map an object, he create the object with default constructor (therefor all the members assign to null) and then add it to MappingContextImpl.sourceToDestination.
BUT,
when there is no custom converter, the logic keep to update the "destination" object that stored at MappingContextImpl.sourceToDestination.
and when there is custom converter, the object that stored at MappingContextImpl.sourceToDestination remains with all the members assign to null. Since after he convert the object he not updating the destination object that stored at MappingContextImpl.sourceToDestination.

Therefor I can't use my custom converter when same instance of object might return multiple times.

What should I do?

**Comment by chhsiao90** [comment]
Hi @almoghzn , Sorry for the lately reply. I'm trying to understand your case, I have some questions for you.

*1. Is ```name``` a field of Source*
*2. What's your destination class?*
*3. What's your expectation result*

And let me correct you about the data after map:
```
Source (31)
name:String = null
Source (32)
name:String = null
```

should be

```
Source (33)
name:String = null
Source (34)
name:String = null
```

That these two sources should be different to the first Screen in the list, am I right?

**Comment by almoghzn** [comment]
![image](https://user-images.githubusercontent.com/16574356/41236881-dee3d372-6d9a-11e8-94e5-50d6e667bd6f.png)

Hi, thanks for the reply.

Let me try to clarify,
In the above picture I tried to demonstrate my data model, 
note:
0. In parenthesis is the instance id to emphasize the similarity or difference of the instances.
1. I have two instance of Show (100 and 200).
2. Each Show contains Screen. Both of the Show(s) contains the same Screen instance (10).
3. The Screen contains two Source(s) (1 and 2).
4. The Source contains String property/field which called "name".

So, for your questions:
1. Yes, name is a field of Source as I mentions at #4.
2. My destination class is List<ShowDTO>
My source class is List<Show>
Assume that ShowDTO and Show are identical. i.e. have the same properties/fields.
3. 
Source:
![image](https://user-images.githubusercontent.com/16574356/41237817-286e3e18-6d9d-11e8-8c50-4b27e24398a2.png)

Expected:
![image](https://user-images.githubusercontent.com/16574356/41237872-5278fba8-6d9d-11e8-817b-ac56c3875a87.png)

(The objects changed from Show / Screen / Source to ShowDTO / ScreenDTO / SourceDTO and the data remain the same. i.e. the data was copied successfully).

Actual:
![image](https://user-images.githubusercontent.com/16574356/41237949-8c917aae-6d9d-11e8-9a54-590f3c71c0dc.png)

(The objects changed to *DTO as I mentioned above. BUT, noticed, the property/field "name" of Source is **null** for the second ShowDTO (200)

Hope it clarify more the issue.

Fill free to contact and ask for more information as it's important to me to resolve this.

Thanks!

**Comment by chhsiao90** [comment]
The explanation looks good to me and I think I can try to reproduce this issue. I will keep you updated. Thanks.

**Comment by chhsiao90** [comment]
hi @almoghzn ,

I can't reproduce this issue, here is my unit test.

```java
import java.util.Arrays;
import java.util.List;
import org.modelmapper.AbstractTest;
import org.modelmapper.TypeToken;
import org.testng.annotations.Test;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertSame;

@Test
public class GH297 extends AbstractTest {
  static class Show {
    Show(Screen sreen) {
      this.sreen = sreen;
    }
    Screen sreen;
  }

  static class Screen {
    Screen(List<Source> sources) {
      this.sources = sources;
    }
    List<Source> sources;
  }

  static class Source {
    Source(String name) {
      this.name = name;
    }
    String name;
  }

  static class ShowDto {
    ScreenDto sreen;
  }

  static class ScreenDto {
    List<SourceDto> sources;
  }

  static class SourceDto {
    String name;
  }

  public void shouldMap() {
    Screen screen = new Screen(Arrays.asList(
        new Source("a"),
        new Source("b")));
    List<Show> source = Arrays.asList(
        new Show(screen),
        new Show(screen));
    List<ShowDto> destination = modelMapper.map(source, new TypeToken<List<ShowDto>>() {}.getType());

    assertEquals(destination.size(), 2);
    assertEquals(destination.get(0).sreen.sources.size(), 2);
    assertEquals(destination.get(1).sreen.sources.size(), 2);
    assertSame(destination.get(0).sreen.sources.get(0), destination.get(1).sreen.sources.get(0));
    assertSame(destination.get(0).sreen.sources.get(1), destination.get(1).sreen.sources.get(1));
  }
}

```

**Comment by almoghzn** [comment]
Hi @chhsiao90 

First, noticed, one big missing part is that you don't have CustomConverter for Source class as I mentioned in my first post.

Second, I tried as well to reproduce the issue using your test code and it didn't work for me at all.

My code (copied by yours) as follow:

`import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.TypeToken;

import java.util.Arrays;
import java.util.List;

import static junit.framework.TestCase.assertSame;
import static org.junit.Assert.assertEquals;

/**
 * Created by Almog on 12/06/2018.
 */
public class GH297 {

    static class Show {
        Show(Screen sreen) {
            this.sreen = sreen;
        }

        Screen sreen;
    }

    static class Screen {
        Screen(List<Source> sources) {
            this.sources = sources;
        }

        List<Source> sources;
    }

    static class Source {
        Source(String name) {
            this.name = name;
        }

        String name;
    }

    static class ShowDto {
        ScreenDto sreen;
    }

    static class ScreenDto {
        List<SourceDto> sources;
    }

    static class SourceDto {
        String name;
    }

    @Test
    public void shouldMap() {

        ModelMapper modelMapper = new ModelMapper();

        Screen screen = new Screen(Arrays.asList(
                new Source("a"),
                new Source("b")));
        List<Show> source = Arrays.asList(
                new Show(screen),
                new Show(screen));
        List<ShowDto> destination = modelMapper.map(source, new TypeToken<List<ShowDto>>() {
        }.getType());

        assertEquals(destination.size(), 2);
        assertEquals(destination.get(0).sreen.sources.size(), 2);
        assertEquals(destination.get(1).sreen.sources.size(), 2);
        assertSame(destination.get(0).sreen.sources.get(0), destination.get(1).sreen.sources.get(0));
        assertSame(destination.get(0).sreen.sources.get(1), destination.get(1).sreen.sources.get(1));
    }
}
`

I'm using gradle so I put this line at the build.gradle file:
`compile 'org.modelmapper:modelmapper:2.0.0'`

While debugging, source object is:
![image](https://user-images.githubusercontent.com/16574356/41277886-20b6d7d6-6e31-11e8-83d8-954b46903a06.png)


and destination object is:
![image](https://user-images.githubusercontent.com/16574356/41277931-3bb22d42-6e31-11e8-8f34-25964cf6df9d.png)

**Comment by chhsiao90** [comment]
hi @almoghzn ,

Please add following code to configure your to ModelMapper.
ModelMapper is using getter/setter by default.
So the mapping will fail if you don't have any getter/setter OR you don't enable the field matching.

```java

    modelMapper.getConfiguration()
        .setFieldMatchingEnabled(true)
        .setFieldAccessLevel(AccessLevel.PACKAGE_PRIVATE)
        .setMethodAccessLevel(AccessLevel.PACKAGE_PRIVATE);
```

And can you tell me how you configure the converter to the modelmapper?

**Comment by almoghzn** [comment]
Hi @chhsiao90 

So I managed to reproduce this issue.
I'll start from the end - at you latest version it's seems to be working well!

With:
`compile 'org.modelmapper:modelmapper:0.7.3'`

I get the following result:

![image](https://user-images.githubusercontent.com/16574356/41290440-88cb6e9e-6e55-11e8-9680-cd51963a8f22.png)

Which is unexpected result as I mentioned in my first post.


But, with:
`compile 'org.modelmapper:modelmapper:2.0.0'`

I get the following result:

![image](https://user-images.githubusercontent.com/16574356/41290542-de265de0-6e55-11e8-9e52-c44b7a9ab449.png)

Which is perfect and expected result!
