### ISSUE TITLE
Inheritance mapping for unknown child types during runtime

### ISSUE THREAD

**Issue by mdzhigarov** [modelmapper/modelmapper#298]
I have some complex hierarchy of source class types, which have a common parent class. Same for destination types - many child types which have a common parent.

I do not know every source/destination child class type. New child types may come and go during runtime.

I am trying to map a source type do destination type.
I have defined an explicit mapping for the parent types.

When I call map(srcParent, DestParent.class) -> I get null for every field, since the srcParent reference actually points to an actual Src type for which I have not defined mapping.

How can I deal with this use case?

Example code that demonstrates this (currently failing):
https://github.com/mdzhigarov/modelmapper/commit/26a931a2402eaaed06a6d33cbda0b7894aa9a5e6

**Comment by chhsiao90** [comment]
Please try http://modelmapper.org/user-manual/type-map-inheritance/

```
modelMapper.addMappings(...);
modelMapper.typeMap(SrcBase.class, DestBase.class).include(Src.class, Dest.class)
```

**Comment by mdzhigarov** [comment]
This works fine but one has to know the Src type in advance in order to register a new type map. I do not know all child types in advance so this won't work for me.

I considered using a conditional converter with partial match. This looks promising.

**Comment by chhsiao90** [comment]
Different implementation/sub-classes might have different mappings, so I don't intent to change the behavior here. ConditionConverter should be fine to use.
