### ISSUE TITLE
Add deep cloning feature

### ISSUE THREAD

**Issue by prinal10** [modelmapper/modelmapper#307]
It will be nice to add a deep cloning of the same object. Something like this:

User user1 = modelMapper.map(user, User.class);

**Comment by optimm** [comment]
In this , the LocalDate field from one is getting null in the copy
```
        this.modelMapper = new org.modelmapper.ModelMapper();
        this.modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
        this.modelMapper.getConfiguration().setDeepCopyEnabled(true);
```

**Comment by pgl-celum** [comment]
I have the same issue with dates as @optimm 
@chhsiao90 is there a way to overcome it?
