### ISSUE TITLE
no mapping fields java.util.Optional<any Collections>

### ISSUE THREAD

**Issue by robbiepl** [modelmapper/modelmapper#313]
source object:
```
Optional<Set<String>> cc;
```
destination object:
```
Set<String> cc;
```

mapping to cc -> null;

**Comment by chhsiao90** [comment]
I will provide modelmapper-module-jdk8 to support this.

**Comment by chhsiao90** [comment]
Should be supported by https://github.com/chhsiao90/modelmapper-module-java8
