### ISSUE TITLE
setSkipNullEnabled(true) is null skip, I want String blank skip.

### ISSUE THREAD

**Issue by MS-Song** [modelmapper/modelmapper#319]
Hello. 
I use ModelMapper well.

I want config String is "" or "  "  skip mapping all object.

I know Null value skip is 
modelMapper.getConfiguration().setSkipNullEnabled(true);
OR
modelMapper.getConfiguration().setPropertyCondition(Conditions.isNotNull());

But, How to String is Blank Skip config?

Thx.

**Comment by chhsiao90** [comment]
Is your source an object or a string? Can you provide an example? Thanks.

**Comment by MS-Song** [comment]
I found it. 

// string blank condition
Condition<?, ?> isStringBlank = new AbstractCondition<Object, Object>() {
    @Override
	public boolean applies(MappingContext<Object, Object> context) {
	if(context.getSource() instanceof String) {
		return null!=context.getSource() && !"".equals(context.getSource());
	} else {
		return context.getSource() != null;
	}
    }
};
ModelMapper modelMapper = new ModelMapper();
modelMapper.getConfiguration()
	.setSkipNullEnabled(true)				
	.setPropertyCondition(**isStringBlank**)			
	.setSourceNamingConvention(NamingConventions.NONE)	
	.setDestinationNamingConvention(NamingConventions.NONE)	
	.setMatchingStrategy(MatchingStrategies.STRICT)

**Comment by chhsiao90** [comment]
So if we have this, the mapped will not be invoked if source.name or source.address is empty?

```java
class Source {
  private String name;
  private String address;
}

class Destination {
  private String name;
  private String address;
}
```
