### ISSUE TITLE
How can I map a list of dto?

### ISSUE THREAD

**Issue by timur-sh** [modelmapper/modelmapper#326]
I looking for a way for mapping a list of dto using modelmapper. Is it possible?

For example:
```
mapper.map(userList, ArrayList<UserDto>.getClass());
```

**Comment by prince-jn** [comment]
I think you have to create a new list and then add each item mapped.

**Comment by chhsiao90** [comment]
Can you try like this https://github.com/modelmapper/modelmapper/blob/master/core/src/test/java/org/modelmapper/functional/iterable/CollectionMapping1.java

**Comment by timur-sh** [comment]
Thank you. It's worked pretty good.
