### ISSUE TITLE
Skip fields that are not explicitly mapped

### ISSUE THREAD

**Issue by gintautassulskus** [modelmapper/modelmapper#327]
Suppose I have a type map such as `TypeMap<Source, Dest> typeMap`. 
Is it possible to either clear predetermined mappings or skip them and map only manually specified properties?

**Comment by chhsiao90** [comment]
Please try set ImplicitMappingEnabled false before setup any TypeMap
```java
modelMapper.getConfiguration().setImplicitMappingEnabled(false)
```

**Comment by gintautassulskus** [comment]
Thanks, this is exactly what I need but per TypeMap basis. 
Would it make sense to request such a feature?

**Comment by chhsiao90** [comment]
Please try
```java
Configuration conf = modelMapper.getConfiguration().copy().setImplicitMappingEnabled(false);
TypeMap<Source, Dest>typeMap = modelMapper.createTypeMap(Source.class, Dest.class, conf);
typeMap.addMappings(mappings);
```

**Comment by gintautassulskus** [comment]
Oh, missed this. Thanks very much, @chhsiao90.
