### ISSUE TITLE
ClassCastException in ModelMapper: EnhancerByModelMapper cannot be cast

### ISSUE THREAD

**Issue by imtiazShakil** [modelmapper/modelmapper#329]
The details can be found in this link:
https://stackoverflow.com/questions/32127438/classcastexception-in-modelmapper-enhancerbymodelmapper-cannot-be-cast

I'm using modelMapper 1.1.0 and still experiencing this problem

**Comment by imtiazShakil** [comment]
There is a dirty solution for this problem posted on stackoverflow.

**Comment by chhsiao90** [comment]
hi @imtiazShakil ,
Recently, I tried to reproduce this issue but failed (please refer #254), can you provide a reproducible sample project / code for me? Thanks.

**Comment by imtiazShakil** [comment]
Hi,

I checked Issue#254. After adding this line into `spring-devtools.properties`,  the problem gets fixed. It's actually 

`restart.include.modelmapper=/modelmapper-(.*).jar`

I think this special scenario should be added in modelMapper Getting Started page as most spring developers will face this situation.

Thanks.

**Comment by chhsiao90** [comment]
I will, thanks for the advice.

**Comment by chhsiao90** [comment]
Docs update here: http://modelmapper.org/user-manual/spring-boot-devtools-integration/

**Comment by imtiazShakil** [comment]
Thanks!
