### ISSUE TITLE
Map an object to two different objects

### ISSUE THREAD

**Issue by coperfield86** [modelmapper/modelmapper#332]
Hello 
I need map a object to two different object for example that differ in some attributes
Regards

**Comment by chhsiao90** [comment]
You can call twice `modelMapper.map(source, Dest.class) like
```java
Dest1 dest1 = modelMapper.map(source, Dest1.class);
Dest2 dest2 = modelMapper.map(source, Dest2.class);
```

Is that what you are asking?

**Comment by chhsiao90** [comment]
Please feel free to reopen this issue if you still had problem.
