### ISSUE TITLE
Pass external properties when calling ModelMapper.map(...)

### ISSUE THREAD

**Issue by bsadykov** [modelmapper/modelmapper#339]
I need to do mapping based on language, which I receive as parameter in rest-controller. In my JPA-entity I have list of translations and I need to put only one translation in DTO.
Maybe the external properties could be added to MappingContext so that they are accessible from converters ?

**Comment by chhsiao90** [comment]
Is ```ThreadLocal``` can help for your case?
```threadLocal.set(language)``` before you map, ```threadLocal.get()``` in your converter, ```threadLocal.remove()``` after you map.

**Comment by bsadykov** [comment]
Yes, I ended up using interceptor + thread local, which has some advantages over external properties.
Thank you for commenting with the solution.
Still would be nice to have external properties, I can see some cases where thread local may not be enough.

**Comment by chhsiao90** [comment]
Sounds good to me about the idea of eternal properties. But I think MappingContext is not a good place to hold these values.

To simplify the requirement here is:
There are some user custom properties that will used by the converter/provider, but these properties are not exist in the source properties.

Is this right? I will consider to have these improvement.

**Comment by bsadykov** [comment]
Sorry, for the late reply. Sounds great to me ! Would be very helpful in
some cases.
