### ISSUE TITLE
typeMap#addMapping casting issue

### ISSUE THREAD

**Issue by Kidlike** [modelmapper/modelmapper#340]
On the following sample:
```
.addMapping(Item::getFocusPoint, (dst, v) -> dst.getImageDTO().setFocusPoint((FocusPoint) v));
```

The `FocusPoint` casting isn't safe.
I.E. if either source or destination attribute `focusPoint` is refactored to another type,
neither the compiler nor `modelMapper.validate()` will catch it.

Are there any solutions here?
Maybe a new `addMapping` override with more or different arguments?
Ideally `v` should be typed and not casted.

**Comment by chhsiao90** [comment]
I think it's safe here to cast. Or maybe you prefer this way:
```
.addMapping(Item::getFocusPoint, (Deste dst, FocusPoint v) -> dst.getImageDTO().setFocusPoint(v));
```
