### ISSUE TITLE
ModelMapper skip null fields not working with Map

### ISSUE THREAD

**Issue by r-dimitrov** [modelmapper/modelmapper#341]
I'm trying to map (source) **RoadAssistanceDto** to (destination) **RoadAssistance**. Both have **Map<Locale, RoadAssistanceI18n>** property and id property.

```
public class RoadAssistanceDto{

 private Long id;
 private Map<Locale, RoadAssistanceI18n> roadAssistanceI18n

 // GETTERS AND SETTRS ///
}

public class RoadAssistance{

 private Long id;
 private Map<Locale, RoadAssistanceI18n> roadAssistanceI18n

 // GETTERS AND SETTRS ///
}


public class RoadAssistanceI18n{

private Long id;
private String description;

// GETTERS and settres/

}

```

The problem I want to preserve the RoadAssistanceI18n id in the RoadAssistance.

The simple test case:
```
@Test
void testMapper(){

    RoadAssistanceDto roadAssistanceDto = new RoadAssistanceDto();
    RoadAssistanceI18n roadAssistanceDtoI18n = new RoadAssistanceI18n();
    roadAssistanceDtoI18n.setDescription("NEW DESCRIPTION");
    roadAssistanceDto.setRoadAssistanceI18n(Locale.ENGLISH,roadAssistanceDtoI18n);

    RoadAssistance roadAssistance = new RoadAssistance();
    RoadAssistanceI18n roadAssistanceI18n = new RoadAssistanceI18n();
    roadAssistanceI18n.setId(10L);
    roadAssistanceI18n.setDescription("OLD DESCRIPTION");
    roadAssistance.setRoadAssistanceI18n(Locale.ENGLISH,roadAssistanceI18n);

    ModelMapper mapper = new ModelMapper();
    mapper.getConfiguration().setPropertyCondition(Conditions.isNotNull());

    mapper.map(roadAssistanceDto,roadAssistance);

    System.out.println(roadAssistance.getRoadAssistanceI18n(Locale.ENGLISH).getId());
    System.out.println(roadAssistance.getRoadAssistanceI18n(Locale.ENGLISH).getDescription());

}
```
and the result is

> null
> NEW DESCRIPTION

The description filed is overridden from the source (RoadAssistanceDto) which is perfect, but the id is set to null. I want to preserve the id to 10 (which is set to RoadAssistance)

**Comment by chhsiao90** [comment]
hi @r-dimitrov,
You need to add a converter for `roadAssistanceDto.roadAssistanceI18n -> roadAssistance.roadAssistanceI18n `.

```java
modelMapper.getConfiguration().setDeepCopyEnabled(true);

Converter<Map<Locale, RoadAssistanceI18n>, Map<Locale, RoadAssistanceI18n>> converter = context -> new HashMap(context.getSource());
modelMapper.typeMap(RoadAssistanceDto.class, RoadAssistance.class)
  addMappings(mapper -> mapper.using(converter).map(RoadAssistanceDto::getRoadAssistanceI18n,
    RoadAssistance::setRoadAssistanceI18n));
```

**Comment by reidomath** [comment]
> hi @r-dimitrov,
> You need to add a converter for `roadAssistanceDto.roadAssistanceI18n -> roadAssistance.roadAssistanceI18n `.
> 
> ```java
> modelMapper.getConfiguration().setDeepCopyEnabled(true);
> 
> Converter<Map<Locale, RoadAssistanceI18n>, Map<Locale, RoadAssistanceI18n>> converter = context -> new HashMap(context.getSource());
> modelMapper.typeMap(RoadAssistanceDto.class, RoadAssistance.class)
>   .addMappings(mapper -> mapper.using(converter).map(
>         RoadAssistanceDto::getRoadAssistanceI18n,
>         RoadAssistance::setRoadAssistanceI18n));
> ```

Hi @chhsiao90 , I had a similar problem, and solved it only with: 

modelMapper.getConfiguration().setDeepCopyEnabled(true);

Thanks

**Comment by Arsennikum** [comment]
It's a real problem. I have a default value (`new HashMap<>()`) which is set in a constructor. But next, I have NPE, because my empty map has been rewritten by null

**Comment by Arsennikum** [comment]
Eah, I've solved it by
```java
modelMapper.getConfiguration().setPropertyCondition(context ->
    context.getSource() != null || !Map.class.isAssignableFrom(context.getSourceType()) 
);
```
