### ISSUE TITLE
Create destination object according to destination context

### ISSUE THREAD

**Issue by git-developer** [modelmapper/modelmapper#346]
I have a question concerning the following scenario:

```java
class Container<T> {
  final Class<T> type;
  T value;
  Container(Class<T> type) {
    this.type = type;
  }
}

class Destination {
  Container<Foo> foo;
  Container<Bar> bar;
  ... // many other fields
  
  Container<?> create(String propertyName) {
    if ("foo".equals(propertyName)) { foo = new Container(Foo.class); }
    if ("bar".equals(propertyName)) { bar = new Container(Bar.class); }
    ... // many other properties
  }
}
```

When `mapper.map(someSource, Destination.class);` is called, an exception is thrown because `Container` doesn't have a default constructor. My idea is to solve the problem with a custom Provider:
```java
class ContainerProvider implements Provider<Container<?>> {
  Container<?> get(ProvisionRequest<Container<?>> request) {
    Class<?> targetType = ???;
    return new Container(targetType);
  }
}
``` 

Unfortunately this doesn't work because the provider is unable to determine the target type.
It needs access to the name or exact type of the target property, but `ProvisionRequest` exposes the source object and the `Class` of the destination (without generic type) only.

Is it possible to solve this problem without a custom converter per property?

**Comment by git-developer** [comment]
Thank you for your quick response and for the test case.

Unfortunately, the source types differ from the destination types, and they need type conversion.

It seems to me that ModelMapper does not cover this use case, so I wrote a workaround: the destination object is instantiated manually, and the `create()` method is called for the concerned properties. All that happens before `modelMapper.map()` is called. The workaround is sufficient to solve my problem. From my point of view, this issue may be closed.

**Comment by chhsiao90** [comment]
Thanks for raising this issue even you already solve this problem.

Agreed with you about that ModelMapper doesn't cover this use case.
It's always hard to solve generic type issues because this types only exist in compile time, and we can't know the real type in the runtime.
