### ISSUE TITLE
Reuse of mappings within an object tree

### ISSUE THREAD

**Issue by vb-chris** [modelmapper/modelmapper#354]
_Previously asked on [Stackoverflow](https://stackoverflow.com/questions/50841898/)_

Please have a look at the following example that illustrates my question.

- Class `Sub` contains several properties.
- Class `Source` contains an object of type `Sub` and (at least) another property.
- Class `Destination` holds a flat list of properties.
- The types of source and destination properties differ.

Code:
```java
    @Test
    public class GH354 {

      ModelMapper modelMapper = new ModelMapper();

      class Source {
        String value1 = "1.0";
        Sub sub = new Sub();
      }

      class Sub {
        String sub1 = "2.0";
        String sub2 = "3";
      }

      class Destination {
        float numberOne;
        double numberTwo;
        int numberThree;
      }

      GH354() {
        modelMapper.addMappings(new PropertyMap<Sub, Destination>() {
            @Override
            protected void configure() {
                map(source.sub1, destination.numberTwo);
                map(source.sub2, destination.numberThree);
            }
        });
        modelMapper.addMappings(new PropertyMap<Source, Destination>() {
            @Override
            protected void configure() {
                map(source.value1, destination.numberOne);
                // map(source.sub, destination); // this causes an exception
            }
        });
      }

      public void mapSub() { // works
        Destination destination = new Destination();
        modelMapper.map(new Sub(), destination);
        assertEquals(destination.numberTwo, 2d);
        assertEquals(destination.numberThree, 3);
      }

      public void mapSource() { // how to make this work?
        Destination destination = new Destination();
        modelMapper.map(new Source(), destination);
        assertEquals(destination.numberOne, 1f);
        assertEquals(destination.numberTwo, 2d);
        assertEquals(destination.numberThree, 3);
      }
    }
```

I'm looking for a way to configure a single ModelMapper instance so that the following constraints are satisfied:

 1. `modelMapper` is able to convert objects of type `Sub` to `Destination`
 2. `modelMapper` is able to convert objects of type `Source` to `Destination`
 3. the mapping of the properties in `Sub` is declared only once

Unfortunately, the line `map(source.sub, destination);` seems not not work as desired. 

My real world scenario contains a bigger object tree with more properties and type conversion. That's the reason why I try to avoid redundant mapping information.

Is it possible to satisfy the constraints?

  [1]: http://modelmapper.org/

**Comment by chhsiao90** [comment]
I'm working on this by providing a new API ```includeChild(SourceGetter, ChildType)```

But there is some limitation that our SourceGetter can only support the getter method invocation, we can't support for field access.

**Comment by vb-chris** [comment]
I'd love to evaluate your extension. Unfortunately, I cannot build the project by myself (because the build dependencies are blocked by our firewall) and I didn't find a way to get the jar from travis. Thus, I'm looking forward to the release of version 2.0.1

**Comment by chhsiao90** [comment]
Just release v2.1.0, please take a look.

**Comment by vb-chris** [comment]
I checked the release, works as announced.
Thank you very much!

The problem is solved for me, the issue may be closed.
