### ISSUE TITLE
OSGI bundle manifest Import-Package contains non-existing packages

### ISSUE THREAD

**Issue by geichelberger** [modelmapper/modelmapper#363]
When using modelmapper as osgi bundle wiring fails because of a package that does not exist as dependency. 

Generated Manifest File Import:
> Import-Package: javax.xml.datatype, org.modelmapper.builder,org.modelma
>  pper.config,org.modelmapper.internal.asm.commons, sun.misc

Missing package:
> org.modelmapper.internal.asm.commons

**Comment by chhsiao90** [comment]
hi @mdzhigarov,

Sorry for bothering you, and idea on this issue? I'm not familiar with OSGi, thanks.

**Comment by mdzhigarov** [comment]
Sorry, I am not familiar with the latest modepmapper changes. 
Last time I checked, osgi classloading was working fine. You just need to enable the osgi classloader bridging option in the config.
No idea if the bridging classloader still works with the new bytebuddy stuff

**Comment by chhsiao90** [comment]
Thanks for the advise, I will try by my self if there is any issues with the new bytebuddy stuff.

**Comment by geichelberger** [comment]
Byte Buddy repackages the asm-commons dependency which is missing in model mapper. After adding the dependency to the dependencies list of the core pom.xml the shade plugin repackages the missing package and the generated OSGi manifest seems to be correct.

**Comment by chhsiao90** [comment]
hi @geichelberger, is #369 solve this issue? Thanks!

**Comment by chhsiao90** [comment]
I will cut a release this week!

**Comment by chhsiao90** [comment]
I just release v2.1.1, please have a look, thanks.
