### ISSUE TITLE
TypeMap order problem

### ISSUE THREAD

**Issue by kurdyukovpv** [modelmapper/modelmapper#367]
Hi!
I have two TypeMap
``` 
modelMapper.createTypeMap(Address.class, AddressDto.class)
                .addMapping(s -> s.getCoordinates().getX(), (d, value) -> d.setLongitude(String.valueOf(value)))
                .addMapping(s -> s.getCoordinates().getY(), (d, value) -> d.setLatitude(String.valueOf(value)));
```

```
modelMapper.createTypeMap(CityObject.class, CommonObjectDto.class)
                .addMapping(BaseEntity::getId, (d, v) -> d.setCityObjectId((Long) v));
```

CityObject and CommonObjectDto contains Address and AddressDto inside of them.

It works fine, but if i change order of creation TypeMap then "Address mapper" isn't work.

```
modelMapper.createTypeMap(CityObject.class, CommonObjectDto.class)
````
```
modelMapper.createTypeMap(Address.class, AddressDto.class)
```

**Comment by chhsiao90** [comment]
Currently, different order of type map will have different behavior.

A TypeMap is constructed with mappings that each mapping define how a source property maps to a destination property. The TypeMap's mappings is defined when it created.

For your first case, ModelMapper knows how Address maps to AddressDto, so it will create the mapping(CityObject.address -> CommonObjectDto.address) in the TypeMap(CityObject -> CommonObjectDto).
For your second case, ModelMapper don't know how to map Address->AddressDto when it tried to create property mapping between CityObject.address and CommonObjectDto.address.

So for your first case, you will have
```
TypeMap(Address->AddressDto)
    mapping(coordinates.x -> longitude)
    mapping(coordinates.y -> latitude)

TypeMap(CityObject -> CommonObjectDto)
    mapping(id -> cityObjectId)
    mapping(address -> address)
```

But for your second case, model mapper don't know how to 
```
TypeMap(Address->AddressDto)
    mapping(coordinates.x -> longitude)
    mapping(coordinates.y -> latitude)

TypeMap(CityObject -> CommonObjectDto)
    mapping(id -> cityObjectId)
```

**Comment by kurdyukovpv** [comment]
So sad :(
Thanks for answer!
