### ISSUE TITLE
Protobuf module throws NoSuchMethodException for list type

### ISSUE THREAD

**Issue by chhsiao90** [modelmapper/modelmapper#392]
See https://github.com/modelmapper/modelmapper/issues/265#issuecomment-417865087

**Comment by chhsiao90** [comment]
Currently, protocol buffer module is not supporting the repeat field. I will work on this.

**Comment by dineshsriram** [comment]
Any updates on this, @chhsiao90 ?

**Comment by augustojaba** [comment]
The bug is simple, the reflection code used to access the object in the issue is not expecting this method to have an argument.

**Comment by chhsiao90** [comment]
Fixed by #518. Can somebody take a look if the patch fix this issue? Thanks!

**Comment by nosovj** [comment]
Any progress on this issue @chhsiao90?

**Comment by chhsiao90** [comment]
Pull request merged, I'm planing to have a release this week.

**Comment by chhsiao90** [comment]
ModelMapper 2.4.0 released.
