### ISSUE TITLE
Result of mapping field (type: Collection) with 2.1.1 and 2.20 is different from 0.7.4

### ISSUE THREAD

**Issue by pkalinkina** [modelmapper/modelmapper#393]
Hello, I wanted to ask what is expected behaviour in the following case:

I have an entity class:
```
@Data
@AllArgsConstructor
public class Car {
    private Collection<Types> list;
}
```
and a DTO class:
```
@Data
@AllArgsConstructor
public class CarDto {
    private Collection<Types> list;
}
```
`@Data` and `@AllArgsConstructor` are annotations from Lombok to generate setters/getters

And I have the following test:
```
    @Test
    public void testCollectionMapping() {
        ModelMapper mapper = new ModelMapper();

        ArrayList<Types> one = new ArrayList<>();
        one.add(Types.ONE);

        ArrayList<Types> two = new ArrayList<>();
        two.add(Types.ONE);
        two.add(Types.TWO);

        CarDto carDto = new CarDto(two);
        Car car = new Car(one);

        mapper.map(car, carDto);
        assertEquals(one, carDto.getList());
    }
```

It passes if I use model mapper 0.7.4, but fails when I use 2.1.1 or 2.2.0. 
The error: 
```
java.lang.AssertionError: 
Expected :[ONE]
Actual   :[ONE, TWO]
```

If I add this configuration when using 2.1.1 or 2.2.0:
```
 mapper.createTypeMap(Car.class, CarDto.class).addMappings(mapping -> {
                    mapping.map(Car::getList, CarDto::setList);
                }
        );
```
results doesn't change

**Comment by chhsiao90** [comment]
Please check #386 that we change the behavior of mapping collections.

Explained here: https://github.com/modelmapper/modelmapper/issues/386#issuecomment-414918810 and workaround: https://github.com/modelmapper/modelmapper/issues/386#issuecomment-414928196

**Comment by pkalinkina** [comment]
Thank you for the fast reply! The workaround helped

Just wondering, have you considered to make a property for collection mapping strategy? 
For example 
REWRITE:
```
modelMapper.map(Source(items=[a, b]), Destination(items=[e, f, g])
// Destination become Destination(items=[a, b])
```
APPEND:
```
modelMapper.map(Source(items=[a, b]), Destination(items=[e, f, g])
// Destination become Destination(items=[e, f, g, a, b])
```
DEFAULT:
```
modelMapper.map(Source(items=[a, b]), Destination(items=[e, f, g])
// Destination become Destination(items=[a, b, g])
```

So this behaviour can be set once on mapper level

**Comment by chhsiao90** [comment]
Sorry...I'm not very interested for introducing new API for this.
