### ISSUE TITLE
Provider to collection

### ISSUE THREAD

**Issue by agdolla** [modelmapper/modelmapper#409]
Hi
My problem is somewhat similar to #248 , I'd like to map a collection to other collection, but I'd like to provide the instances manually for every item.
My problem is something like this:
```java
class SourceClassInner {
 ...
}

class DestinationClassInner {
 ...
 SomeType type;
 public DestinationClass(SomeType type) { this.type = type; }
}

class SourceClass {
  SourceClassInner p1;
  Collection<SourceClassInner> p2;
}

class DestinationClass {
  DestinationClassInner p1;
  Collection<DestinationClassInner> p2;
}

...
with(req -> new DestinationClassInner(SomeType.TYPE1)).map(source.getP1(), destination.getP1());
with(req -> new DestinationClassInner(SomeType.TYPE2)).map(source.getP2(), destination.getP2());
```

the second mapping does not work, is it possible to have a Provider for a Collection ?

thanks
Gabor

**Comment by chhsiao90** [comment]
Hi @agdolla ,

Can you take a look https://github.com/modelmapper/modelmapper/blob/master/core/src/test/java/org/modelmapper/bugs/GH248.java#L63-L69 if it can fixed you problem?
Thanks!

**Comment by agdolla** [comment]
Hi @chhsiao90 
That project is finished by now, so I close this ticket. If it comes back again and your fix does not work I'll reopen it.
Thanks for you efforts!!!
