### ISSUE TITLE
Collection items are not removed if source is smaller than destination

### ISSUE THREAD

**Issue by q-src** [modelmapper/modelmapper#423]
We use modelmapper in a RESTful API for mapping dtos to entities. Therefore, we expect the items missing in `source` being removed from `destination` when the collection / array mapping is done in a child context.

Example:
```java
Dto dto = new Dto();
dto.items = Arrays.asList("a", "b");

Entity entity = new Entity();
entity.items = Arrays.asList("a", "b", "c");

mapper.map(dto, entity);
```
After the mapping, we'd expect `entity.items` to equal `{"a", "b"}`. However, it remains unchanged and equals `{"a", "b", "c"}`.

**Comment by chhsiao90** [comment]
It's a design decision when I implemented #387.

Please check comments: https://github.com/modelmapper/modelmapper/issues/386#issuecomment-413526172, https://github.com/modelmapper/modelmapper/issues/386#issuecomment-414918810.

And here is the code you can try with current ModelMapper: https://github.com/modelmapper/modelmapper/issues/386#issuecomment-414928196

**Comment by q-src** [comment]
Thanks for the reply. Now we use custom typeMaps as you suggested.

**Comment by danielhoeppe** [comment]
@chhsiao90 I just encountered the exact same issue when using ModelMapper and expected the same result as @q-src. I'm using ModelMapper in the same use case as @q-src.

What about adding a configuration option specifying the removal of list members when the source size is less than the destination size?
