### ISSUE TITLE
modelmapper cannot be imported in gradle

### ISSUE THREAD

**Issue by Aragami1408** [modelmapper/modelmapper#445]
Even now I still cannot use modelmapper in gradle

To be specific, this is my `build.gradle` file:

```gradle
repositories {
	mavenCentral()
}

dependencies {
	...
	implementation 'org.modelmapper:modelmapper:2.3.0'
	...
}
```

Even though I imported but I cannot import it into my code. How can I deal with this?

**Comment by Chubasic** [comment]
I have the same problem.

**Comment by eviljoe** [comment]
I had this problem as well.  I was able to fix it by adding the following line to my `build.gradle` file:
```
compile 'org.modelmapper:modelmapper:2.3.3'
```

**Comment by Aragami1408** [comment]
Thank @eviljoe. That's totally works fine for me. Thanks for helping

**Comment by KlausDevWalker** [comment]
That works for me too, thanks. But is it not really weird that we have to use an old syntax to make it work?

**Comment by hsuanyi-chou** [comment]
my gradle version is 7, and not working for me.
how to make it work?

**Comment by manojbaishya** [comment]
`compile 'org.modelmapper:modelmapper:3.1.0'` is not supported in Gradle v7.0+. `implementation 'org.modelmapper:modelmapper:3.1.0'` also does not work. Is there any other alternative to this library? Thanks.
