### ISSUE TITLE
Property map difficult to construct types

### ISSUE THREAD

**Issue by jhalterman** [modelmapper/modelmapper#46]
When attempting to property map types which are difficult to construct, errors may occur. Ex: BigInteger and BigDecimal have restrictive constructors and require specific default values.

Add handling for difficult to construct types so they can be property mapped.

From: https://groups.google.com/forum/#!topic/modelmapper/2Xh2D6IB-EU

**Comment by saranshbansal** [comment]
It's 2023 and I just faced this issue. The modelmapper is not mapping `BigInteger` and `BigDecimal` fields across entities. There is no exception or warning thrown beforehand.

version: `3.1.1`
