### ISSUE TITLE
Slow explicit mapping using addMapping() method

### ISSUE THREAD

**Issue by TumanovViktor** [modelmapper/modelmapper#462]
Hi,
I am trying to configure explicit mapping of my objects using ModelMapper#addMapping. I have a lot of fields to map and every call of .addMapping lasts for 20-40 ms. It results in the huge spring context start duration. 

I tried to create new clean spring boot project and duration of one call reduced to 10-20 ms, but still it is too much. I have tens of mappers with hundreds of fields and my spring context starts in 4 mins atm. 

In some case, while configuring of explicit mapping lasts for 1 min, implicit is done in 50 ms. How is it possible? What am I doing wrong? 

Thank you.

Here is configuration example:
```
modelMapper.getConfiguration().setImplicitMappingEnabled(false);

modelMapper.createTypeMap(TestDto.class, TestModel.class)
	.addMapping(TestDto::getField, TestModel::setField)
	.addMapping(TestDto::getField2, TestModel::setField2)
	.addMapping(TestDto::getField4, TestModel::setField4)
	.addMapping(TestDto::getField5, TestModel::setField5)
	.addMapping(TestDto::getField6, TestModel::setField6)
	.addMapping(TestDto::getField7, TestModel::setField7)
	.addMapping(TestDto::getField3, TestModel::setField3)
	.addMapping(TestDto::getField8, TestModel::setField8)
	.addMapping(TestDto::getField9, TestModel::setField9)
	.addMapping(TestDto::getField10, TestModel::setField10)
	.addMapping(TestDto::getField11, TestModel::setField11)
	.addMapping(TestDto::getField12, TestModel::setField12)
	.addMapping(TestDto::getField13, TestModel::setField13)
	.addMapping(TestDto::getField14, TestModel::setField14)
	.addMapping(TestDto::getField15, TestModel::setField15)
	.addMapping(TestDto::getField16, TestModel::setField16)
	.addMapping(TestDto::getField17, TestModel::setField17)
	.addMapping(TestDto::getField18, TestModel::setField18)
	.addMapping(TestDto::getField19, TestModel::setField19)
	.addMapping(TestDto::getField20, TestModel::setField20)
	.addMapping(TestDto::getField21, TestModel::setField21)
	.addMapping(TestDto::getField22, TestModel::setField22)
	.addMapping(TestDto::getField23, TestModel::setField23)
	.addMapping(TestDto::getField24, TestModel::setField24)
	.addMapping(TestDto::getField25, TestModel::setField25);

```

**Comment by petercatalin** [comment]
Hi @TumanovViktor !

I'm experiencing the same problem. Did you find any alternatives? The same think is happening to my app and it's extremely frustrating to wait so long for the spring context to load.

**Comment by TumanovViktor** [comment]
Hi @petercatalin ,
unfortunately I didn't find any solutions, I guess the problem is just in the algorithm, which is using proxies...

**Comment by petercatalin** [comment]
@TumanovViktor I noticed that the startup time is way lower with version 2.3.2; but that version has this issue #442 which prevents me from using it. If that is not a problem for you give it a try.

**Comment by petercatalin** [comment]
@TumanovViktor 

It's the implicit mapping that takes so long, but what I said about the versions is still true. The next test
executes in 7s with version 2.3.2 and in 21s with 2.3.3. When I have the time I'm going to create a separate issue.

Please note that the `Application` object has loads of other complex objects and collections. 

```java
  @Test
  public void test_how_long_model_mapper_takes_to_map_an_application() {
    ModelMapper modelMapper = new ModelMapper();
    Long start = System.currentTimeMillis();
    modelMapper.typeMap(Application.class, OutboundApplicationDTO.class);
    Long end = System.currentTimeMillis();
    System.out.println("Generating the Application map took: " + (end - start) + " ms");
  }
```

**Comment by KagariSan** [comment]
Hi,

I'm experiencing the same problem with the latest version 2.3.9.

Any way to improve the loading time or bring all the loading into startup time?

**Comment by chhsiao90** [comment]
I'm trying to fix the performance issue in #592

Can you see if it's fixed this issue?


**Note:** please use `addMappings` instead.
```
modelMapper.typeMap(ManyFields.class, ManyFields.class)
        .addMappings(mapper -> {
          mapper.map(ManyFields::getField1, ManyFields::setField1);
          mapper.map(ManyFields::getField2, ManyFields::setField2);
          mapper.map(ManyFields::getField3, ManyFields::setField3);
          mapper.map(ManyFields::getField4, ManyFields::setField4);
          mapper.map(ManyFields::getField5, ManyFields::setField5);
          mapper.map(ManyFields::getField6, ManyFields::setField6);
          mapper.map(ManyFields::getField7, ManyFields::setField7);
          mapper.map(ManyFields::getField8, ManyFields::setField8);
          mapper.map(ManyFields::getField9, ManyFields::setField9);
          mapper.map(ManyFields::getField10, ManyFields::setField10);
        });
```

**Comment by KagariSan** [comment]
@chhsiao90 Hi, #592 build is falling and I don't know how to test this build, should I pull the project and compile it myself?

**Comment by chhsiao90** [comment]
I can deploy a snapshot to maven central tomorrow  so you can use it directly.

**Comment by KagariSan** [comment]
Please inform me as soon as the snapshot available. Thank you a lot!

**Comment by chhsiao90** [comment]
Snapshot deployed: [modelmapper-2.3.10-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/modelmapper/modelmapper/2.3.10-SNAPSHOT/)

**Comment by KagariSan** [comment]
I tried the snapshot. Didn't notice any change in performance. The modelmapper call of the complex object still takes about 15s.
I will set up the test to actually measure the performance differently and report back later.

**Comment by chhsiao90** [comment]
Did you try using the `addMappings` instead of multiple calls of `addMapping`?

**Comment by chhsiao90** [comment]
ModelMapper 2.4.0 released. Can you check if the performance had been improved?  Please fell free to reopen this issue. Thanks.

**Comment by chaserb** [comment]
I upgraded from 2.3.3 to 2.4.5 and I can confirm the performance issue has been fixed. My spring context load time dropped from ~120s down to 29. I'm using a large handful of addMapping() calls, and one addMappings() call.
