### ISSUE TITLE
Create conditional mapping using converter. 

### ISSUE THREAD

**Issue by sergey-soloviov** [modelmapper/modelmapper#463]
I need to set conditional mapping for a property but using my custom converter.
Currently when create a mapping you can set the condition for a mapping or set the converter for mapping.
Please add this little improvement.

**Comment by chhsiao90** [comment]
Do you mean `when(condition).using(converter).map(...)` which is already supported by ModelMapper?

**Comment by sergey-soloviov** [comment]
Yes. 
If this is supported by ModelMapper could you please tell me in which version this could be done and how?

**Comment by chhsiao90** [comment]
My bad, it looks like the when(condition).using(conververt) chain is not supported by`ExpressionMap`.
