### ISSUE TITLE
Problem at merging objects

### ISSUE THREAD

**Issue by UlisesCeca** [modelmapper/modelmapper#481]
I am using the version 2.3.0 of the library.

I am facing an issue where I'm trying to merge two objects. Lets say this object:

```
public final class MyObject {
     private String name;
     private Team team;
}

public final class Team {
     private List<String> members;
}
```

So, what I want to achieve is to update a document in my db, which means getting the object from my db and then setting the non-null properties of that object from the incoming document to it.

My problem is the following:

Imagine this is my object that I want to update:
```
{
     name: "toupdate",
     team: {
           members: ["member1, "member2", "member3"]
     }
}
```

And this is my updated object:

```
{
     name: null,
     team: {
           members: ["member1, "member3"]
     }
}
```

if I do: `mapper.map(object1, object2);` , I get this:

```
{
     name: "toupdate",
     team: {
           members: ["member1, "member3", "member3"]
     }
}
```

when I should be getting this:

```
{
     name: "toupdate",
     team: {
           members: ["member1, "member3"]
     }
}
```

This is also my configuration:

`mapper.getConfiguration().setPropertyCondition(Conditions.isNotNull());`

What am I doing wrong?

Thanks.

**Comment by nfalco79** [comment]
Set merge collection to false.

This duplicates https://github.com/modelmapper/modelmapper/issues/465
https://github.com/modelmapper/modelmapper/issues/457

**Comment by UlisesCeca** [comment]
> Set merge collection to false.
> 
> This duplicates #465
> #457

it's still being merged...
