### ISSUE TITLE
TypeMap::include copies only `mappings` but `preConverter` and `postConverter`

### ISSUE THREAD

**Issue by linarkou** [modelmapper/modelmapper#498]
TypeMap::include copies only `mappings` but `preConverter` and `postConverter`

Exmaple:
```
import lombok.Data;

@Data
class Person {
  String name;
  Address address;
}
@Data
class Address {
  String country;
  String zipCode;
}
@Data
class PersonDTO {
  String name;
  String country;
  String zipCode;
  String region;
}

class PersonConverter {
  ModelMapper modelMapper = new ModelMapper();

  public void configure() {
    modelMapper.emptyTypeMap(Address.class, PersonDTO.class)
      .addMapping(Address::getCountry, PersonDTO::setCountry)
      .addMapping(Address::getZipCode, PersonDTO::setZipCode)
      .setPostConverter(ctx -> convertRegion(ctx.getSource(), ctx.getDestination()));

    modelMapper.emptyTypeMap(Person.class, PersonDTO.class)
      .addMapping(Person::getName, PersonDTO::setName)
      .include(Person::getAddress, Address.class);
  }

  private PersonDTO convertRegion(Address address, PersonDTO personDTO) {
    if (address.getZipCode().startsWith("111")) {
      personDTO.setRegion("SOME REGION");
    } else {
      personDTO.setRegion("UNKNOWN");
    }
  }
  
  public PersonDTO convert(Person person) {
    return modelMapper.map(person, PersonDTO.class);
  }
}

class Main {
  public static void main(String[] args) {
    Person person = new Person();
    person.name = "NAME";
    Address address = new Address();
    address.country = "COUNTRY";
    address.zipCode = "111111";
    Person.setAddress(address);
    
    PersonConverter personConverter = new PersonConverter();
    personConverter.configure();
    PersonDTO dto = personConverter.convert(person);
    System.out.println(dto.region);
  }
}
```
it will print `null`, but I expect to see `SOME REGION`.

**Comment by chhsiao90** [comment]
Hi @linarkou,

It's expected behavior to only include the mappings without providers/converters as it's not type safe.
Please let me know if you have any idea or new api we can introduce on handling for your scenario.
Thanks!

**Comment by chhsiao90** [comment]
I think the type map inheritance is not suitable for your case. I think the converter for the property mapping is what you need.

```java
modelMapper.emptyTypeMap(Person.class, PersonDTO.class)
      .addMappings(mapper -> {
         mapper.map(Person::getName, PersonDTO::setName);
         mapper.map(person -> person.getAddress().getCountry(), PersonDTO::setCountry);
         mapper.map(person -> person.getAddress().getZipCode(), PersonDTO::setZipCode);
         mapper.using(regionConverter).map(person -> person.getAddress().getZipCode(), PersonDTO::setRegion);
      });
```

**Comment by linarkou** [comment]
it is just a simple example, we use more complex combinations of converters in real life.
I think it is not expected behaviour when I want reuse some mappings..

**Comment by chhsiao90** [comment]
It's not type safe to inherit converters from base TypeMap so we decide to not include the converters to the new TypeMap.

Let me improve the code in my previous comment, my point is that we can replace the `postConverter` with custom property mapping. So this property mapping can be included to the new TypeMap when include is called.

```java
  public void configure() {
    modelMapper.emptyTypeMap(Address.class, PersonDTO.class)
      .addMapping(Address::getCountry, PersonDTO::setCountry)
      .addMapping(Address::getZipCode, PersonDTO::setZipCode)
      .addMappings(mapper -> {
          mapper.using(regionConverter).map(Address::getAddress, PersonDTO::setRegion);
      });

    modelMapper.emptyTypeMap(Person.class, PersonDTO.class)
      .addMapping(Person::getName, PersonDTO::setName)
      .include(Person::getAddress, Address.class);
  }
```

I guessed the updated code is more flexible and better than previous one.
I'm not sure if it can solve your problem, from my perspective, it's hard to make it right if converters can be included between TypeMaps.

**Comment by odrotbohm** [comment]
> It's not type safe to inherit converters from base TypeMap so we decide to not include the converters to the new TypeMap.

Can you elaborate on that? Why should that be the case? By definition, a subtype of A exposes all API of A. I.e. if a pre- or post-converter is defined for A, it is applicable to B extends A. Especially if I explicitly register the inclusion via `.include(Source.class, TargetSubtype.class)`. 🤔
