### ISSUE TITLE
Unclear “Getting Started” for Java 8

### ISSUE THREAD

**Issue by neosimsim** [modelmapper/modelmapper#509]
I was a bit confused reading the [Getting Started](http://modelmapper.org/getting-started/) section.

The following code snipped did not work for me. 
```
ModelMapper modelMapper = new ModelMapper();
modelMapper.addMappings(mapper -> {
  mapper.map(src -> src.getBillingAddress().getStreet(),
      Destination::setBillingStreet);
  mapper.map(src -> src.getBillingAddress().getCity(),
      Destination::setBillingCity);
});
```
To get it running I had to call `createTypeMap`

```
ModelMapper modelMapper = new ModelMapper();
modelMapper.createTypeMap(Source.class, Destination.class).addMappings(mapper -> {
  mapper.map(src -> src.getBillingAddress().getStreet(),
      Destination::setBillingStreet);
  mapper.map(src -> src.getBillingAddress().getCity(),
      Destination::setBillingCity);
});
```

Am I doing something wrong or is it possible that the documentation is mixing the pre Java 8 approach with post Java 8?

**Comment by Agh42** [comment]
I would also like to see an answer to this. Anyone?

**Comment by varomorf** [comment]
Personally I didn't understand it until I found a Stackoverflow post telling to use the createTypeMap() method.

**Comment by chhsiao90** [comment]
The documentation was already fixed, thanks for reporting this issue.
