### ISSUE TITLE
ModelMapper - mapping of empty object issue

### ISSUE THREAD

**Issue by samo717** [modelmapper/modelmapper#521]
I noticed a problem when mapping an object which contains a variable assigned to an object with null values, The mapped object contains mentioned variable set to null. 
I know this is difficult to explain, therefore I managed to create very simple github repository to simulate the issue (with failing test).
https://github.com/samo717/modelMapperSim

**Comment by chhsiao90** [comment]
Thanks for reporting this issue, it's conflict to the unit test [GH6](https://github.com/modelmapper/modelmapper/blob/modelmapper-parent-2.4.0/core/src/test/java/org/modelmapper/bugs/GH6.java#L95).

But your scenario makes sense to me, fixed by #601.
