### ISSUE TITLE
Issue with mapping data from java.util.map to jooq record

### ISSUE THREAD

**Issue by kranthi34** [modelmapper/modelmapper#525]
Any one please provide some example configuration and testcase please as am facing same issue

<dependency>
			<groupId>org.modelmapper</groupId>
			<artifactId>modelmapper</artifactId>
			<version>2.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.modelmapper.extensions</groupId>
			<artifactId>modelmapper-jooq</artifactId>
			<version>2.3.0</version>
		</dependency>

<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jooq</artifactId>
		</dependency>

Spring boot 2.0.0

@bean
public ModelMapper modelMapper() {
ModelMapper mapper = new ModelMapper();

	mapper.getConfiguration().addValueReader(new RecordValueReader()).setSkipNullEnabled(true)
			.setPropertyCondition(Conditions.isNotNull());
	return mapper;
}

my custom class

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;

import org.modelmapper.Conditions;
import org.modelmapper.Converter;
import org.modelmapper.ModelMapper;
import org.modelmapper.TypeMap;
import org.modelmapper.jooq.RecordValueReader;
import org.springframework.stereotype.Component;

import com.centerpoint.ars.customutils.ContextUtils;
import com.centerpoint.ars.generated.model.enums.Recordstatus;
import com.centerpoint.ars.generated.model.tables.pojos.Paymentsettlement;
import com.centerpoint.ars.generated.model.tables.records.PaymentsettlementRecord;

@component
public class PaymentSettlementMapper {

private ModelMapper mapper = new ModelMapper();

public ModelMapper getMapper() {
	 mapper.getConfiguration().addValueReader(new RecordValueReader());
	 mapper.getConfiguration().setSkipNullEnabled(true);
	 mapper.getConfiguration().setPropertyCondition(Conditions.isNotNull());
	final Converter<LocalDate, LocalDate> DATE_TO_LOCAL_DATE_CONVERTER = mappingContext -> {
		return mappingContext.getSource();
	};
	final Converter<LocalDate, LocalDate> LOCAL_DATE_TO_DATE_CONVERTER = mappingContext -> {
		return mappingContext.getSource();
	};

	TypeMap<PaymentSettlementDTO, PaymentsettlementRecord> paymentSettlementMapping = mapper
			.getTypeMap(PaymentSettlementDTO.class, PaymentsettlementRecord.class);
	if (paymentSettlementMapping == null) {
		paymentSettlementMapping = mapper.createTypeMap(PaymentSettlementDTO.class, PaymentsettlementRecord.class);
		paymentSettlementMapping.addMappings(mapping -> mapping.using(LOCAL_DATE_TO_DATE_CONVERTER));
	}
	TypeMap<PaymentsettlementRecord, PaymentSettlementDTO> paymentSettlementRecordMapping = mapper
			.getTypeMap(PaymentsettlementRecord.class, PaymentSettlementDTO.class);
	if (paymentSettlementRecordMapping == null) {
		paymentSettlementRecordMapping = mapper.createTypeMap(PaymentsettlementRecord.class,
				PaymentSettlementDTO.class);
		paymentSettlementRecordMapping.addMappings(mapping -> mapping.using(DATE_TO_LOCAL_DATE_CONVERTER));
	}

	TypeMap<HashMap, PaymentsettlementRecord> paymentSettlementMapMapping = mapper.getTypeMap(HashMap.class,
			PaymentsettlementRecord.class);
	if (paymentSettlementMapMapping == null) {
		paymentSettlementMapMapping = mapper.createTypeMap(HashMap.class, PaymentsettlementRecord.class);
		paymentSettlementMapMapping.addMappings(mapping -> mapping.using(LOCAL_DATE_TO_DATE_CONVERTER));
	}
	return mapper;
}

public Paymentsettlement mapToPojoCreate(PaymentSettlementDTO paymentSettlementDto) {
		Paymentsettlement paymentSettlement = mapper.map(paymentSettlementDto, Paymentsettlement.class);
		paymentSettlement.setBalanceamount(paymentSettlementDto.getAmount());
		paymentSettlement.setBranchid(ContextUtils.getContext().getLocationId());
		paymentSettlement.setCreatedip(ContextUtils.getContext().getIpAddress());
		paymentSettlement.setCreatedby(ContextUtils.getContext().getName());
		paymentSettlement.setCreateddate(OffsetDateTime.now());
		paymentSettlement.setStatus(Recordstatus.ACTIVE);
		paymentSettlement.setCompanyid(paymentSettlementDto.getCompanyid());
		return paymentSettlement;
}

public PaymentsettlementRecord mapToPojoToUpdate(Map<String, Object> paymentDto, PaymentsettlementRecord paymentRecord) {
	getMapper().map(paymentDto, paymentRecord);
	paymentRecord.setUpdateddate(OffsetDateTime.now());
	paymentRecord.setUpdatedby(ContextUtils.getContext().getName());
	paymentRecord.setUpdatedip(ContextUtils.getContext().getIpAddress());
	return paymentRecord;
}
}

and i want to map

mapper.map(Hashmap.class, jooqrecord.class)

but some fields are not mapping even though the field names are same in both java.util.map and record
ex:- balanceamount in both map and record column name

**Comment by hgwz** [comment]
Is this issue resolved？I met similar issue when converting map to jooq record，very appreciate if any resolution or clue。
