### ISSUE TITLE
Many Thread Blocked by PropertyInfoRegistry#accessorFor method

### ISSUE THREAD

**Issue by wyzssw** [modelmapper/modelmapper#528]
org.modelmapper.internal.PropertyInfoRegistry#accessorFor(java.lang.Class<?>, java.lang.reflect.Method, org.modelmapper.config.Configuration, java.lang.String)

I see the code will execute alway enter into accessorFor but not hit in cache,

>  if (!ACCESSOR_CACHE.containsKey(hashCode) || !FIELD_CACHE.containsKey(hashCode)) 

 
  static Accessor accessorFor(Class<?> type, String accessorName, InheritingConfiguration configuration) {
    Integer hashCode = hashCodeFor(type, accessorName, configuration);
    if (!ACCESSOR_CACHE.containsKey(hashCode) || !FIELD_CACHE.containsKey(hashCode)) {
      @SuppressWarnings("unchecked")
      Class<Object> uncheckedType = (Class<Object>) type;
      for (Entry<String, Accessor> entry : TypeInfoRegistry.typeInfoFor(uncheckedType, configuration).getAccessors().entrySet()) {
        if (entry.getValue().getMember() instanceof Method)
          accessorFor(type, (Method) entry.getValue().getMember(), configuration, entry.getKey());
        else if (entry.getValue().getMember() instanceof Field)
          fieldPropertyFor(type, (Field) entry.getValue().getMember(), configuration, entry.getKey());
      }
    }

    if (ACCESSOR_CACHE.containsKey(hashCode))
      return ACCESSOR_CACHE.get(hashCode);
    return FIELD_CACHE.get(hashCode);
  }

**Comment by jhalterman** [comment]
Related to #520

**Comment by jhalterman** [comment]
Fixed in 2.3.7.
