### ISSUE TITLE
Anonymous enums are not detected correctly

### ISSUE THREAD

**Issue by pwinckles** [modelmapper/modelmapper#534]
[EnumConverter](https://github.com/modelmapper/modelmapper/blob/master/core/src/main/java/org/modelmapper/internal/converter/EnumConverter.java#L45) (and potentially other locations) does not correctly test if an object is an enum. It calls `sourceType.isEnum()` which returns `false` for anonymous enums. According to [this bug report](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6708424), this is intended behavior and the correct way to identify whether or not an object is an enum is by `object.getDeclaringClass().isEnum()`.

That said, perhaps the bug is actually [here](https://github.com/modelmapper/modelmapper/blob/master/core/src/main/java/org/modelmapper/internal/MappingEngineImpl.java#L266), where it attempts to resolve the class of the source object.

**Comment by chhsiao90** [comment]
Can you provide reproducible code for this issue? Thanks!

**Comment by malteo** [comment]
@chhsiao90 I stumbled into this bug after trying to upgrade from 2.3.2 to 2.3.3, and it is indeed still not working in 2.4.0

I opened a PR which seems to fix
