### ISSUE TITLE
can not mapping nested collections of map

### ISSUE THREAD

**Issue by kangarooxin** [modelmapper/modelmapper#547]
`
    @Test
    public void test1() {
        Map<Integer, List<Product>> productListMap = new HashMap<>();
        productListMap.put(1, Arrays.asList(
                new Product().setProductId(1L).setProductName("product1"),
                new Product().setProductId(2L).setProductName("product2")
        ));
        Type listType = new TypeToken<Map<Integer, List<ProductVo>>>(){}.getType();
        Map<Integer, List<ProductVo>> result = BeanUtils.map(productListMap, listType);
        System.out.println(result.get(1).get(0).getClass().getName());
       //java.lang.ClassCastException: Product cannot be cast to ProductVo
    }

    @Data
    @Accessors(chain = true)
    public static class Product {

        private Long productId;

        private String productName;
    }

    @Data
    @Accessors(chain = true)
    public static class ProductVo {

        private Long productId;

        private String productName;
    }
    `

**Comment by abekthink** [comment]
I'm having the same issue.

**Comment by chhsiao90** [comment]
Thanks for reporting this bug, should be fixed by #599

**Comment by chhsiao90** [comment]
ModelMapper v2.4.1 was just released including the fix.
