### ISSUE TITLE
Make TypeMaps work with superclasses of mapping sources

### ISSUE THREAD

**Issue by ToWi87** [modelmapper/modelmapper#551]
Hello,
I have some trouble mapping inherited source classes with the ModelMapper:

**Situation:**
- abstract class: **Fruit**
- class: **Apple extends Fruit**
- class: **Banana extends Fruit**
- DTO class: **FruitDTO**

Now the root of the problem is that I couldn't simply register a `Provider` for the Fruit -> FruitDTO TypeMap.
I managed to sail around registering the same provider for both - Apple and Banana - separately.

Where I really run into problems is when working with mocks in tests. There even the two separate configurations won't help, because there I have the mock proxy objects. And a `Apple$MockitoMock` is not an `Apple`...

Is it possible in future to make TypeMaps work also for subclasses of the registered classes? Or at least also de-proxy source types? I found the following for destination types
`engine.<Object, D>map(source, Types.<Object>deProxy(source.getClass()), destination,
        TypeToken.<D>of(destinationType), typeMapName);`
in `ModelMapper#573` but I can't estimate the final impacts also in other places.

**Comment by chhsiao90** [comment]
I guessed [Type Map Inheritance](http://modelmapper.org/user-manual/type-map-inheritance/) is what you are looking for.

**Comment by cdalexndr** [comment]
> I guessed [Type Map Inheritance](http://modelmapper.org/user-manual/type-map-inheritance/) is what you are looking for.

This is a tedious manual approach. An automatic mechanism should be made:

1. When creating a typemap, a check should be made if a typemap for a base type exists and inherit it automatically.
2. Inheriting typemap doesn't inherit provider/converter/etc.

Please change this form `Question` to `Feature request.
