### ISSUE TITLE
A function that can map list of objects

### ISSUE THREAD

**Issue by abhisht7** [modelmapper/modelmapper#558]
I have been using this library and had cases where I would pull list of entities from database and map it to the DTO. I ended up creating a utility function that would map all objects of the list. 
I think having a map function which accepts list can be useful. 
I can open a PR if this sounds good.

**Comment by ajans** [comment]
You can use the standard map function if you define the destination listType like this (replace `List<String>` with your actual type):

`Type destinationListType = new TypeToken<List<String>>() {}.getType();`

Then you can use it with map:

`List<String> characters = modelMapper.map(sourceList, destinationListTypeListType);`

Solution taken from this documentation page:
http://modelmapper.org/user-manual/generics/
