### ISSUE TITLE
jOOQ RecordValueReader.getMember().getValueType() should return Field's type ?

### ISSUE THREAD

**Issue by akisei** [modelmapper/modelmapper#563]
(Sorry, this sentence was translated by Google Translate.)

I found a problem when using with jOOQ.

I have an entity class with an enum type field and I wanted to use `Converter` to convert from `org.jooq.Field<Integer>`.
But `RecordValueReader.getMember(source, memberName).getValueType()` always returns `Record.class`, so Converter mapping is not resolved.

This is the code for this part.

> ```java
>   public Member<Record> getMember(Record source, String memberName) {
>     return new Member<Record>(Record.class) {
>       @Override
>       public Object get(Record source, String memberName) {
>         return RecordValueReader.this.get(source, memberName);
>       }
>     };
>   }
> ```

For example, I want to change it like this. (This code is not perfect.)

> ```java
>   public Member<Record> getMember(Record source, String memberName) {
>     Field<?> field = matchField(source, memberName);
>     return new Member<Record>(field.getType()) { // FIXME: this code is not null safe.
>       @Override
>       public Object get(Record source, String memberName) {
>         return RecordValueReader.this.get(source, memberName);
>       }
>     };
>   }
> ```

What do you think of this issue?

**Comment by chhsiao90** [comment]
Thanks for reporting this issue, the feature sound good, addressed by #598

**Comment by chhsiao90** [comment]
ModelMapper v2.4.1 was just released including the fix.
