### ISSUE TITLE
Class files compiled for Java 15 not supported when configuring ModelMapper instance with PropertyMap

### ISSUE THREAD

**Issue by jo-ka** [modelmapper/modelmapper#564]
If a `ModelMapper` instance is configured using a `PropertyMap`, which is the workaround I found for https://github.com/modelmapper/modelmapper/issues/480 and https://github.com/modelmapper/modelmapper/issues/511, it looks like ASM is used to read the class files. That is, _only_ in this case, i.e. ASM is _not_ used when configuring using an ExpressionMap.

If those class files were compiled to the Java 15 format, this leads to an exception in `org.modelmapper.internal.asm.ClassReader.<init>` like this: "Unsupported class file major version 59".

According to https://asm.ow2.io/versions.html, it looks like support for Java 15 was added in ASM 7.3.1. The ModelMapper POM defines a dependency on ASM 7.2, and I presume that the repackaged internal classes are based on 7.2, too.

So it's probably necessary to bump the ASM version to at least 7.3.1.

**Comment by jo-ka** [comment]
Thanks @nicktar and @chhsiao90!

**Comment by jo-ka** [comment]
I tested my project with a locally built 2.3.9-SNAPSHOT version and that does indeed fix this issue. It would be great if you could make a 2.3.9 release version soon. :)

**Comment by chhsiao90** [comment]
Hi @jo-ka , sorry for the lately reply, 2.3.9 just released, it would be available soon in maven central.

**Comment by jo-ka** [comment]
Thanks again!
