### ISSUE TITLE
Cycles in object graph lead to wrong mapping based on entry point

### ISSUE THREAD

**Issue by qzagarese** [modelmapper/modelmapper#565]
Hi there,
thank you for building modelmapper: it's a great library!

If have found out that cycles are not always correctly detected and this can lead to incorrect mappings (beside creating unnecessary instances). Consider the following structure where:
- A chessboard contains a list of nodes and a node has a reference to the board it belongs to.
- A node has a list of pieces (e.g. like in checkers)
- A player has a favourite piece and a favourite node of the chessboard.

Now let's say we have two identical class structures: one representing the persistence layer and one for domain objects (Apologies for the long snippet).

```java

// domain entities
@Getter
@Setter
@NoArgsConstructor
public class ChessBoard {
    private List<BoardNode> nodes;
}

@Getter
@Setter
@NoArgsConstructor
public class BoardNode {
    private List<ChessPiece> pieces;
    private ChessBoard board;
    private int x;
    private int y;
}

@Getter
@Setter
@NoArgsConstructor
public class ChessPiece {
    private String id;
    private BoardNode node;
}

@Getter
@Setter
@NoArgsConstructor
public class Player {
    private BoardNode favoriteTile;
    private ChessPiece favoritePiece;
}

// DB equivalent
@Getter
@Setter
@NoArgsConstructor
public class DBChessBoard {
    private List<DBBoardNode> nodes;
}

@Getter
@Setter
@NoArgsConstructor
public class DBBoardNode {
    private List<DBChessPiece> pieces;
    private DBChessBoard board;
    private int x;
    private int y;
}

@Getter
@Setter
@NoArgsConstructor
public class DBChessPiece {
    private String id;
    private DBBoardNode node;
}

@Getter
@Setter
@NoArgsConstructor
public class DBPlayer {
    private DBBoardNode favoriteTile;
    private DBChessPiece favoritePiece;
}

```

Finally here is a test that creates some DB entities and maps them to domain ones:

```java
    @Test
    public void test() {
        ModelMapper mapper = new ModelMapper();

        DBBoardNode dbNode1 = new DBBoardNode();
        dbNode1.setX(0);
        dbNode1.setY(0);

        DBBoardNode dbNode2 = new DBBoardNode();
        dbNode2.setX(1);
        dbNode2.setY(1);

        DBChessPiece dbChessPiece = new DBChessPiece();
        dbChessPiece.setId(UUID.randomUUID().toString());
        dbChessPiece.setNode(dbNode1);
        dbNode1.setPieces(Arrays.asList(dbChessPiece));

        DBChessBoard dbChessBoard = new DBChessBoard();
        dbChessBoard.setNodes(Arrays.asList(dbNode1, dbNode2));
        dbNode1.setBoard(dbChessBoard);
        dbNode2.setBoard(dbChessBoard);

        DBPlayer dbPlayer = new DBPlayer();
        dbPlayer.setFavoritePiece(dbChessPiece);
        dbPlayer.setFavoriteTile(dbNode2);

        ChessBoard chessBoard = mapper.map(dbChessBoard, ChessBoard.class);
        Player player = mapper.map(dbPlayer, Player.class);
        System.out.println();
    }

```
If you debug this and get to the last line, you will notice that:
- `chessBoard` is correctly mapped and instances are created exactly once.
- `player` is not mapped correctly. Multiple instances of `ChessBoard` are created, even though there is one instance of `DBChessBoard`. More importantly, the path `player.favoritePiece.node.board.nodes` is incorrectly mapped as `nodes` contains node [1, 1] twice, whilst node [0, 0] has disappeared.
- If `dbPlayer.setFavoriteTile` is commented out (`favoriteTile` is null), the behaviour is even more bizarre: `player.favoritePiece.node.board.nodes` is almost correct (values are but multiple instances of `ChessBoard` are created), however, `player.favoriteTile` is not null!

Please let me know if there's anything I can do to help as this bug is putting a big a chunk of my business logic at risk and I don't want to replace modelmapper.

**Comment by qzagarese** [comment]
@jhalterman  @chhsiao90 I'm happy to take on this myself and contribute a fix, however, I'd need any of you to give me a primer on how you approached circular dependencies management. I could only find a test here `org.modelmapper.bugs.CircularMappingBug`, but it seems to only consider the simplest case.
Happy to jump on a call if of you is available.
Thanks

**Comment by qzagarese** [comment]
Unfortunately I had to give up on this and ultimately switch to MapStruct, however this could be solved fairly quickly if it was possible to inject a behaviour similar to the one described here https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-mapping-with-cycles/src/main/java/org/mapstruct/example/mapper
Best

**Comment by chhsiao90** [comment]
ModelMapper 2.4.0 released.
