### ISSUE TITLE
some config work in java8, java11, but not work in java13

### ISSUE THREAD

**Issue by WangZemin0816** [modelmapper/modelmapper#567]
In typetools.TypeResolver static initial filed, i find follow:

**_Field overrideField = AccessibleObject.class.getDeclaredField("override");_**

This can run in java8 and 11, but will throw no such method exception in java13, which may cause some model mapper config can run in java11 but cant run in java13

**Comment by chhsiao90** [comment]
Need to be fixed from typetools side, there is already one issue opened for this (see https://github.com/jhalterman/typetools/issues/70)

**Comment by chhsiao90** [comment]
Fixed and released in v2.4.1
