### ISSUE TITLE
Using Conditions.isNull to skip setting a destination value is not working as expected.

### ISSUE THREAD

**Issue by IMZEYAULHAQUE** [modelmapper/modelmapper#574]
@Data
    public class PersonEntity {
     private String fName;
     private String lName;
     private Integer age;
     private String city;
    }
    
    public class TestProgram {
    
      // Dummy method to create PersonEntity object
      private static PersonEntity aPersonEntity() {
        PersonEntity entity = new PersonEntity();
        entity.setFName("FirstName");
        entity.setLName("LastName");
        entity.setAge(40);
        entity.setCity("dummyCity");
        return entity;
     }
    
    private static void testEntity2Entity() {
        PersonEntity entity = aPersonEntity();
        PersonEntity entity1 = aPersonEntity();
        entity.setCity("test");
    
        modelMapper().map(entity, entity1);
        System.out.println(entity1);
     }
    
    public static ModelMapper modelMapper() {
        ModelMapper modelMapper = new ModelMapper();
        TypeMap<PersonEntity, PersonEntity> typeMap2 = modelMapper.createTypeMap(PersonEntity.class, PersonEntity.class);
        typeMap2.addMappings(mapper -> mapper.when(Conditions.isNull()).skip(PersonEntity::setCity));
        return modelMapper;
     }
    
    }

Now in this program, expected behavior is entity1 will print city as "test" but it print "dummyCity". Don't know if I am dong  wrong or lib has some issue?

**Comment by micobarac** [comment]
I have the similar issue.

This is working:

`mapper.when(Conditions.isNotNull()).map(AccountUpdateVM::getPackets, Account::setPackets);`

This is **NOT** working:

`mapper.when(Conditions.isNull()).skip(Account::setPackets);`

**Comment by micobarac** [comment]
The other problem is the following...

This works:

```java
        Condition<AccountUpdateVM, Account> packets = context -> {
            AccountUpdateVM source = (AccountUpdateVM) context.getParent().getSource();
            return source.getPackets() != null;
        };
```

I have to extract source and destination from parent, because root source and destination are both NULL values.

This doesn't work:

```java
        Condition<AccountUpdateVM, Account> packets = context -> {
            AccountUpdateVM source = context.getSource(); // This is null
            return source.getPackets() != null; // This causes null pointer exception
        };
```

My classes are not subclassed, nor they are related to each other.

**Comment by chhsiao90** [comment]
Duplicate to #588 

Please check my comment https://github.com/modelmapper/modelmapper/issues/588#issuecomment-805402088

Maybe you should use `when(isNull()).map(...)` instead of `when(isNull()).skip(...)`

**Comment by chhsiao90** [comment]
ModelMapper 2.4.0 released.
