### ISSUE TITLE
map function invalidate if model names are similar

### ISSUE THREAD

**Issue by jakkapongz** [modelmapper/modelmapper#589]
I have 2 Models

```
HouseRequest {
    villageId,
    houseNumber,
    soi
}
```
```
HouseEntity {
    id,
    villageId,
    houseNumber,
    soi
}
```

I would like map request to entity After map id should be null but the result as the same `id` and `villageId`

please see the picture below

![modelmapper_x1](https://user-images.githubusercontent.com/10509037/111896114-d2dee200-8a49-11eb-8992-ff7a0cd6e090.png)

Thanks

**Comment by chhsiao90** [comment]
Please try to use the `STRICT` matching strategy (see [Matching Strategy](http://modelmapper.org/user-manual/configuration/#matching-strategies)

**Comment by jakkapongz** [comment]
@chhsiao90 thanks for replied after config the matching strategy it's working fine!

this issue can close
