### ISSUE TITLE
Error mapping models with jdk 11.0.11 update

### ISSUE THREAD

**Issue by Roman-Skripka** [modelmapper/modelmapper#606]
Yesterday oracle jdk 11.0.11 was released and mapping stopped working with the following error (model mapper version 2.3.9):
```
...
Caused by: org.modelmapper.MappingException: ModelMapper mapping errors:

1) Error mapping a.b.c.ModelA to a.b.c.ModelB

1 error
	at org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:380)
	at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:81)
	at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:573)
	at org.modelmapper.ModelMapper.map(ModelMapper.java:495)
	... 254 common frames omitted
Caused by: java.lang.ClassCastException: null
```

MM configuration:
```
// ... here are some custom converters
modelMapper.getConfiguration().setFieldMatchingEnabled(true).setMatchingStrategy(MatchingStrategies.STRICT).setFieldAccessLevel(
            Configuration.AccessLevel.PRIVATE).setUseOSGiClassLoaderBridging(true);
```

Rolling back to jdk 11.0.10 resolved the issue. Tried updating the library to 2.4.0 but it made no changes.

**Comment by chhsiao90** [comment]
Can you provide reproducible code or more detailed information? Thanks.

**Comment by Roman-Skripka** [comment]
Sure, will do once I have the time to investigate this further.

**Comment by jobinvjohn** [comment]
This is issue is reproducing for us also. 
org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:380) [modelmapper-2.3.9.jar!/:na]\n\tat org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:81) [modelmapper-2.3.9.jar!


Caused by: java.lang.ClassCastException: null

**Comment by jobinvjohn** [comment]
This will get resolved after restarting the server in our case and will get reproduced again after code is there in live for some time.

**Comment by GabrielCORDIER** [comment]
Hey guys, any update on this one ? we have the exact same weird behavior with adopOpenJDK 11.0.11+9 in production.

Rollling back to previous LTS version fix mapping behavior...As it is critical for our company, how can we help ?

**Comment by Roman-Skripka** [comment]
@GabrielCORDIER please provide a failing test case if you can. I don't have an allocation to work on this issue myself and honestly don't know when I will since this is not a high priority for us.

**Comment by PimW** [comment]
I managed find a simple example to generate the same exception, the exception is thrown after a couple hunderd iterations.
This was tested using modelmapper version  2.3.9 and openjdk version 11.0.11

```java
import org.modelmapper.ModelMapper;

import java.util.Map;
import java.util.Set;

public final class ModelMapperFactory {
    static class Baz {
        public void setStrings(Set<String> strings) {}
    }

    static class Foo {
        public Map<String, String> getStringToStringMap() { return Map.of() }
    }
    
    static class Bar {
        public void setBaz(Baz baz) {}
    }

    public static void createInstance() {
        ModelMapper mapper = new ModelMapper();

        mapper.createTypeMap(Foo.class, Bar.class).addMappings(m -> m.skip(Bar::setBaz));
    }

    public static void main(String[] args) {
        while(true) {
            createInstance();
        }
    }
}
```

**Comment by chhsiao90** [comment]
I can reproduce this issue now, thanks @PimW for the reproducible code.

Currently, I have no idea about the root cause, I guessed it's side effect caused by [JDK-8255544](https://bugs.openjdk.java.net/browse/JDK-8255544).

**Comment by chhsiao90** [comment]
It looks like it's caused by the change of JIT compiler optimization in [JDK-8257594](https://bugs.openjdk.java.net/browse/JDK-8257594). But the root cause hadn't been found.

I'm trying to fix the issue by #611. Can anyone in this thread check if the issue was fixed or not by the pull request?

**Comment by chhsiao90** [comment]
Minimum reproducible code created: https://github.com/chhsiao90/jdk-8257594-bug

Already submit a bug report to oracle.

**Comment by chhsiao90** [comment]
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8266615

**Comment by michalbzowski** [comment]
> It looks like it's caused by the change of JIT compiler optimization in [JDK-8257594](https://bugs.openjdk.java.net/browse/JDK-8257594). But the root cause hadn't been found.
> 
> I'm trying to fix the issue by #611. Can anyone in this thread check if the issue was fixed or not by the pull request?

Hi, I've checked this fix and it is working in my case. 
Thank You!

**Comment by Roman-Skripka** [comment]
@chhsiao90 I confirm the issue here doesn't reproduce on the latest master version.

**Comment by chhsiao90** [comment]
ModelMapper v2.4.3 released!

**Comment by chhsiao90** [comment]
FYI: The bug from java side was fixed in 11.0.13.

**Comment by yomal** [comment]
Is this fixed? I am still getting the error with 2.4.3 and OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
This only occurs after about thousands of iterations. Any solution for this?

**Comment by yomal** [comment]
Got the same error with model mapper 2.4.3 and OpenJDK Runtime Environment 18.9 (build 11.0.11+9), 
Getting the error  `Caused by: java.lang.ClassCastException: null` only after multiple iterations (around 1000). Anyone having the same issue even after the version upgrade?

**Comment by khursid-jbl** [comment]
We are facing the very similar behaviour on production since last couple of days.  We are using java-11-amazon-corretto. We had no change in jdk since long.  The issue is intermittent and exists only in some of the containers of the same service.
Can anybody tell what can be the probable issue and resolution?
