### ISSUE TITLE
Not mapping when change setter method parram

### ISSUE THREAD

**Issue by letanloc1998** [modelmapper/modelmapper#607]
NóI have a entity with attribute/field type String.
And DTO type String.
When I change setter method, this field is null. How to fix it?

```java
@Getter
@Setter
public class Entity {
    private String field;
}
```

```java
@Getter
@Setter
public class Dto {
    @Setter(AccessLevel.None)
    private String field;

    public void setField(String ...field) {
        this.field = String.join(",", field);
    }
 
    public void setField(String field) {
        this.field = field
    }
}
```

```java
ModelMapper mapper = new ModelMapper();
mapper.map(entity, Dto.class); // entity.field = "a,b" => mapper result field is null
```

Thank you

**Comment by chhsiao90** [comment]
By default, ModelMapper select a setter if the method matched below conditions.
- Has only one parameter
- Return type is void or the declaring class

So random method will be selected when there are multiple methods matched.
ModelMapper should have better strategy to select one of the conflict methods.
Before the issue fixed, I suggest you can use explicit mapping.

```
    DestinationSetter<Dto, String> setter = Dto::setField;
    modelMapper.typeMap(Entity.class, Dto.class).addMapping(Entity::getField, setter);
```

**Comment by letanloc1998** [comment]
Thank you
