### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by xianqiangzhao** [modelmapper/modelmapper#616]
surroundings
version :2.3.5
spring boot

errormessage: mappingExeption
at org.modelmapper.internal.Errors.throwMappingExceptionIfErrorsExist(Errors.java:380) ~[modelmapper-2.3.5.jar!/:?]
at org.modelmapper.internal.MappingEngineImpl.map(MappingEngineImpl.java:81) ~[modelmapper-2.3.5.jar!/:?]
at org.modelmapper.ModelMapper.mapInternal(ModelMapper.java:573) ~[modelmapper-2.3.5.jar!/:?]
at org.modelmapper.ModelMapper.map(ModelMapper.java:406) ~[modelmapper-2.3.5.jar!/:?]
   Omit

This error will occasionally come out in the aws ecs environment, but it is not found in the local development environment
Can a solution be found, thank you!

**Comment by xianqiangzhao** [comment]
https://github.com/modelmapper/modelmapper/blob/master/core/src/main/java/org/modelmapper/internal/Errors.java

In the code below, you can type out the error in Throwable and estimate the root cause.
==========================================================
  public Errors errorMapping(Object source, Type destinationType, Throwable t) {
    return addMessage(t, "Error mapping %s to %s", source, Types.toString(destinationType));
  }

**Comment by benjaminwai** [comment]
+1 We have run into the same exception as well. We are on 2.3.7 and on Spring Boot too. Looking at our logs it seems like this exception began shortly after the Java runtime changed to 11.0.11 from 11.0.10 in our case - we are using openjdk:11-jdk-slim. From Docker hub openjdk:11.0.11* first appeared around April 28 matching our problem time frame. It may just be a coincidence. We are trying to look into this and other factors at the moment. It is difficult to recreate - the occurrences were intermittent, it may not occur at all. When it did it affected a subset of the classes for the duration of the service. When service was restarted, if it occurred again it would affect a different subset of classes. Any ideas would help..

**Comment by chhsiao90** [comment]
The JDK issue was already fixed in 11.0.13 (Not sure when it would be released).
You can choose to upgrade ModelMapper to v2.4.3 or wait for the JDK release.

**Comment by xianqiangzhao** [comment]
Thanks !!

**Comment by jithintkuriakose** [comment]
We are also facing same issue with version 2.3.9 and we are using openjdk11 image. As per [official page](https://wiki.openjdk.java.net/display/JDKUpdates/JDK11u), openjdk11 still has two more releases for v11.0.13. So, we are going with upgrading modelmapper version to 2.4.3. 
I'll update here if it is resolved our problem.
