### ISSUE TITLE
addMapping NullPointerException

### ISSUE THREAD

**Issue by cdalexndr** [modelmapper/modelmapper#621]
```
        ModelMapper modelMapper = new ModelMapper();
        TypeMap<JPAProduct, Product> typeMap = modelMapper.typeMap( JPAProduct.class, Product.class );
        typeMap.addMapping( p -> p.getJPAProperties().stream()
                                    .map( productPropertyService::toDTO )
                                    .collect( toList() ),
                            Product::setProperties );
```

NPE is thrown because `p.getJPAProperties()` returns `null`. 
The `p` object is enhanced by ByteBuddy. My real objects never return `null`.

Stacktrace:
```
<my lambda code>
visitSource:89, ReferenceMapExpressionImpl (org.modelmapper.internal)
map:63, ReferenceMapExpressionImpl (org.modelmapper.internal)
addMapping:260, TypeMapImpl (org.modelmapper.internal)
```

JDK zulu-11
ModelMapper 2.4.4

**Comment by chhsiao90** [comment]
HI @cdalexndr ,

The `typeMap.addMapping(sourceGetter, destinationSetter)` only accepts a simple getter and a simple setter.
Please use converter instead.

```
typeMap.addMappings(mapper -> mapper.using(converter).map(JPAProduct::getJPAProperties, Product::setProperties));
```

**Comment by cdalexndr** [comment]
> The `typeMap.addMapping(sourceGetter, destinationSetter)` only accepts a simple getter and a simple setter.

Then the [documentation](http://modelmapper.org/user-manual/property-mapping/) is misleading. It has the following examples:
```
typeMap.addMapping(src -> src.getCustomer().getAge(), PersonDTO::setAge);

typeMap.addMapping(src -> src.getPerson().getFirstName(), (dest, v) -> dest.getCustomer().setName(v));
```

**Comment by chhsiao90** [comment]
It’s chained getter and setter.

cdalexndr ***@***.***>於 2021年6月8日 週二，下午5:59寫道：

**Comment by cdalexndr** [comment]
I see... it seems only getters returning classes can be chained (returns bytebuddy enhanced value), but not Collections.
This should pe noted as a warning inside documentation.

**Comment by cdalexndr** [comment]
Ideally, the code should be changed to not allow this invalid behavior... it's not user friendly.
