### ISSUE TITLE
Modelmapper not skip a object field

### ISSUE THREAD

**Issue by smeligrana** [modelmapper/modelmapper#633]
I have four class

```
public class A {

    private String field1;
    private String field2;

    private B b;

   // setter and getter
}

public class B {

    private String fieldB1;
    private String fieldB2;

   // setter and getter

}

public class ADto {

    private String field1;
    private String field2;

    private BDto b;

   // setter and getter
}

public class BDto {

    private String fieldB1;
    private String fieldB2;

   // setter and getter

}
```

I want to use modelmapper to populate dto objects

```
ModelMapper modelMapper = new ModelMapper();
modelMapper.typeMap(A.class, ADto.class, "LAZY")                
                .addMappings(mapper -> mapper.skip(ADto::setB))
                .addMappings(mapper -> mapper.skip(ADto::setField2));

modelMapper.map(a, ADto.class, "LAZY");
```
I use typeMapName to be able to have more mappers

The mapper correctly skips field2 but instead ignores the skip for B, what am I wrong?

Thanks

**Comment by sok82** [comment]
Good day.
+1

I have the same issue on ModelMapper 2.3.8
I tried to debug mapping an found that it looks like 'incorrect' mapping is generated - it doesn't skip nested fields, while skipping container field.

I.e. mapping looks like 

1. ADto.field1 -> A.field1   - OK
2. [SKIPPED] ADto.field2 -> A.field2 - OK
3. [SKIPPED] ADto.b -> A.b - OK

and then 

4. (!!!NOT SKIPPED) ADto.b.fieldB1 -> A.b.fieldB1 ???
5. (!!!NOT SKIPPED) ADto.b.fieldB2 -> A.b.fieldB2 ???

So it doesn't skip nested properties and in case if object 'A' already exists mapping and is not created in a mapping process - we have problems.

In my case as a consequence I had a Hibernate bug that told me that 'id' of entity 'B' was updated - which took me a great amount of time to debug

Still struggling with it - didn't find how to perform mapping with ModelMapper and had to do it manually
Any help would be appreciated.

**Comment by WubbaLu-bba** [comment]
I would like to work on this issue, I find out that when do the skip()
`this.typeMap.addMapping(this.collector.collect());`
this part won't find the fields of the object so that no name match in the TreeMap.
To solve this, I add a method in class 'ReferenceMapExpressionImpl" that use stack to find all field and form a chain to do the addMapper(). I will add a PR so that you can check my code.

**Comment by chhsiao90** [comment]
Sorry for the lately reply. Can you try https://github.com/modelmapper/modelmapper/issues/654#issuecomment-1001371385 ?

This is how ModelMapper work, maybe we should have FAQ in our website.

**Comment by chhsiao90** [comment]
Error message for skip conflict was added #668, and I will have a new page pitfall in our website. Thanks for reporting this issue.
