### ISSUE TITLE
matches multiple source property hierarchies problem

### ISSUE THREAD

**Issue by ACodeFarmer** [modelmapper/modelmapper#64]
Hi, I'm using JPA(with Hibernate) and wish to convert some composite domain to view layer, So I'm using ModelMapper also. 

At first, I defined some domain and DTO classes.

``` Java
@Entity
public class User {
    ...
    @Id
    String id;

    @OneToOne
    Preference preference;
    ...
}

@Entity
public class Preference {
    ...
    @Id
    String id;

    @OneToOne
    User user;

    BigDecimal money;
    ...
}

public class UserDto {
    ...
    String id;
    BigDecimal preferenceMoney;
    ...
}
```

then, I've tried to mapping DTO object instance to domain object instance.

``` Java
UserDto userDto = new UserDto();
userDto.setPreferenceMoney(1000.0);
mapper.map(userDto, User.class);
```

this code returns error

``` Java
1) The destination property User.setPreference()/Preference.setUser() matches multiple source property hierarchies:
```

Skipping to set user to Preference class suppress this error, but when saving data to persist returned exception that preference object instance couldn't get user property. :(

Is this an another case of circular reference problem? I've dig circular reference test cases, but I can't find a solution.

**Comment by jedionmelbin** [comment]
I have the same problem but with properties of type date

1) The destination property com.infiniteskills.domain.DTO.DocumentoIdentidadDTO.setDocumentoIdentidadId() matches multiple source property hierarchies:

	com.infiniteskills.domain.model.DocumentoIdentidad.getUsuarioCreacionId()
	com.infiniteskills.domain.model.DocumentoIdentidad.getUsuarioModificaId()

**Comment by chhsiao90** [comment]
Thanks for the report.
Could you provide what it look like  of the source class and the destination class?
Or maybe you can provide a minimum reproducer if you cannot provide the source class and destination class.
That will help us to solve your issue, thanks!

**Comment by dharaoza** [comment]
I have the same problem can you please help me to solve.
The destination property com.measureone.vo.OrgApplicationPerson.setPersonParty()/com.measureone.vo.Party.setModifiedByPersonParty() matches multiple source property hierarchies:

	com.measureone.dto.UserDTO.getModifiedByPersonPartyName()
	com.measureone.dto.UserDTO.getModifiedByPersonPartyId()

**Comment by JuricaJaman** [comment]
i am not sure anymore to use modelmapper at all in 2018 still this problem exists

**Comment by mudassir047** [comment]
mapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);

**Comment by franco148** [comment]
Still the problem exists. As the example provide by @ACodeFarmer I have my Jpa Entities with bidirectional relationships. So I am getting the following exception.

**The destination property com..BaseEntity.setId() matches multiple source property hierarchies.........**

The version of org.modelmapper that I am using is: 2.0.0

**Comment by chhsiao90** [comment]
Thanks for the detailed information, I will investigate this bug.

**Comment by chhsiao90** [comment]
hi @franco148 ,

One quick question: are below mappings that you expected?
```
createdById -> comment.id
resourceId -> comment.commentedResource.id
```

**Comment by franco148** [comment]
Sorry, I have not copied all the entities.

**createdById** : is the reference to a Participant entity. So, it would be **comment.createdAt.Id**
**resourceId**: yes, it refereces to **comment.commentedResource.id**

Here the missing entity.

```
@Data
@Entity
public class Participant {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;

    @OneToMany(mappedBy = "sharedBy")
    private Set<ShareAction> shared;
    @OneToMany(mappedBy = "sharedWith")
    private Set<ShareAction> sharedWithMe;
    @OneToMany(mappedBy = "createdBy")
    private Set<Message> messages;
}
```

The diagram for these entities would be something like this.

![image](https://user-images.githubusercontent.com/10811329/40845991-4dbc0cc8-6586-11e8-8b74-bc88a99ac479.png)

So, in the controller I am calling a creation of a comment, which has a reference to a Recourse ID and Participant ID.

Hope that helps.

**Comment by chhsiao90** [comment]
hi @franco148 ,
Our matching strategy is not smart as you think, it has some rules, please refer [matching-strategies|http://modelmapper.org/user-manual/configuration/#matching-strategies] for detail.
For mappings that our matching strategy can't support correctly, please try our [property-mapping|http://modelmapper.org/user-manual/property-mapping/] for customize mappings.

And it's weird that comment.createdAt is a LocalDateTime, I don't think it has a property named id.

**Comment by franco148** [comment]
Hi @chhsiao90 

Sorry it was my mistake in the explanation, I have already updated that comment. comment.createdBy was the correct relation.

Thank you for your support. I will take a look at the resources you are suggesting me.

**Comment by thelebdev** [comment]
Anyone figure this out yet? 👁️
