### ISSUE TITLE
Migration from 2.3.x to 3.1.x

### ISSUE THREAD

**Issue by raf-against-tm** [modelmapper/modelmapper#696]
Hi, I've started using ModelMapper in 2.3.8 version several months ago. I want to upgrade version to latest but APIs are already published and I was wondering is there are any breaking changes between versions to evaluate migration. Are you planning doing a change list, compatibility or something like that?

Thanks!

**Comment by dstango** [comment]
Have a look here: https://github.com/modelmapper/modelmapper/blob/master/CHANGES.md

As far as I see it the main "breaking change" with v3.x.x is that now Java 8 ist the minimum requirement.
