### ISSUE TITLE
Map when source field name start with target field name

### ISSUE THREAD

**Issue by chMatvey** [modelmapper/modelmapper#709]
Hi guys, 
I faced with the problem. Easiest would be share with code example:

    public class ModelMapperTest {
        @Data
        static class Source {
            private boolean campaignParticipant;
        }
    
        @Data
        static class Target {
            private boolean campaignParticipant;
            private String campaign;
        }
    
        @Test
        void map() {
            Source source = new Source().setCampaignParticipant(false);
            ModelMapper modelMapper = new ModelMapper();
            Target target = modelMapper.map(source, Target.class);
    
            System.out.println(target.toString());
            assertNull(target.getCampaign());
        }
    }

So in this example source class contains one field `campaignParticipant`.
And I expect that the target result woulde be `(campaignParticipant=false, campaign=null)`.
But actual I got `(campaignParticipant=false, campaign=false)`. 
Boolean `campaignParticipant` field mapped to `campaign` as a String, see screen below.

![image](https://user-images.githubusercontent.com/40443101/217748005-aa36b686-3b4b-40e2-b35c-2a13b60a70b3.png)

Model mapper version 3.1.1

**Comment by kibedov** [comment]
Hi!

You can use strict matching strategy.
Just try
```
public class ModelMapperTest {
    @Data
    @Accessors(chain = true)
    static class Source {
        private boolean campaignParticipant;
    }

    @Data
    static class Target {
        private boolean campaignParticipant;
        private String campaign;
    }

    @Test
    void map() {
        Source source = new Source().setCampaignParticipant(false);
        ModelMapper modelMapper = new ModelMapper();
        modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
        Target target = modelMapper.map(source, Target.class);

        System.out.println(target.toString());
        assertNull(target.getCampaign());
    }
}
```

Hope this helps

**Comment by chMatvey** [comment]
Hi,
Thank you,
It's works for me
