### ISSUE TITLE
Test fails after upgrading from 3.1.0 to 3.1.1

### ISSUE THREAD

**Issue by du-it** [modelmapper/modelmapper#724]
When upgrading ModelMapper Maven dependency from 3.1.0 to 3.1.1 some previously running tests fail.
I use this Bean:

```
   @Bean
    public ModelMapper partnerProfileMapper() {
        ModelMapper modelMapper = getModelMapperBase(MatchingStrategies.LOOSE);
        modelMapper.typeMap(AccountAndRelatedData.class, PartnerProfile.class)
            .addMappings(mapper -> mapper.using(accountDataConverter(modelMapper))
                .map(AccountAndRelatedData::getAccountAndRelatedDataItem, PartnerProfile::setAccountData))
            .addMappings(mapper -> mapper.using(contactPreferencesConverter(modelMapper))
                .map(AccountAndRelatedData::getAccountAndRelatedDataItem, PartnerProfile::setContactPreferences))
            .addMappings(mapper -> mapper.using(newsletterPreferencesConverter(modelMapper))
                .map(AccountAndRelatedData::getAccountAndRelatedDataItem, PartnerProfile::setNewsletterPreferences))
            .addMappings(mapper -> mapper.using(employeesConverter())
                .map(AccountAndRelatedData::getAccountAndRelatedDataItem, PartnerProfile::setEmployees));

        return modelMapper;
    }
```

Depending on the MatchingStrategy the test fails or succeeds: 

 -     Using MatchingStrategies.LOOSE in 3.1.0 works well.
 -     Using MatchingStrategies.LOOSE in 3.1.1 ends in a org.modelmapper.ConfigurationException: ModelMapper configuration errors: 
  1) Not able to skip accountData., because there are already nested properties are mapped: [accountData.contactId.
 accountData.email. accountData.firstName. accountData.lastName. accountData.mobile. accountData.name.
 accountData.phone.]. Do you skip the property after the implicit mappings mapped? We recommended you to create an
 empty type map, and followed by addMappings and implicitMappings calls
 - Using MatchingStrategies.STRICT in 3.1.0 leads to fail due to some fields are null (which are tested: `assertThat(partnerProfile.getCompanyData()).isNotNull();.`
 - Using MatchingStrategies.STRICT in 3.1.1 leads to fail due to some fields are null (which are tested: `assertThat(partnerProfile.getCompanyData()).isNotNull();.`

How can I let the tests be run successful with ModelMapper 3.1.1?

What does this sentence mean? 
'We recommended you to create an empty type map, and followed by addMappings and implicitMappings calls'

**Comment by rosatownsend** [comment]
The cryptic advice puzzled me too. I'm not sure exactly what changed (it broke my project too), but this is what's happening now and how to fix it:

The "implicit mappings" get added when you create the `TypeMap` (by calling `modelMapper.typeMap(...)`). These automatically include mappings inside nested objects, e.g.

`accountData.item.contactId` to `partnerProfile.accountData.contactId`

Then you're trying to override those ("skip" them, see polite error message) by mapping the whole nested object:
```
modelMapper.typeMap(AccountAndRelatedData.class, PartnerProfile.class)
            .addMappings(mapper -> mapper.using(accountDataConverter(modelMapper))
                .map(AccountAndRelatedData::getAccountAndRelatedDataItem, PartnerProfile::setAccountData));
```
What it wants you to do is (this is what the sentence above means):
```
modelMapper.emptyTypeMap(AccountAndRelatedData.class, PartnerProfile.class) //emptyTypeMap with no implicit mappings
            .addMappings(mapper -> mapper.using(accountDataConverter(modelMapper))
                .map(AccountAndRelatedData::getAccountAndRelatedDataItem, PartnerProfile::setAccountData))
            .implicitMappings(); // explicitly add the implicit mappings if you want them
```

**Comment by chhsiao90** [comment]
Thanks @rosatownsend  for explanation, that's the error about.

It's my bad about introducing the breaking change in a minor release. I think it might be better to have a warning first, and change it to error in a major release.
