### ISSUE TITLE
Java 21 support

### ISSUE THREAD

**Issue by CynanX** [modelmapper/modelmapper#725]
Currently model mapper fails when used with Java 21 due to not supporting major version 65.

Can this be addressed? Or is this project dead? No updates for quite a while and a number of outstanding issues.

**Comment by chvid** [comment]
The master branch is for an unreleased (?) version 3.1.2 and that has a dependency on org.ow2.asm version 9.4 - this needs to be upgraded to version 9.5+ to support Java 21.

So it appears to be easily solved and really just a question of releasing version 3.1.2.

**Comment by atelechev** [comment]
This problem is recurrent, it appears regularly when new Java versions are released.

As @chvid says, the version of the `asm` lib should be updated. Last time [it was done](https://github.com/modelmapper/modelmapper/commit/ebd330128e0a636a4de8c4a497e7f404cd339b38) about a year ago and I think that in most cases this change would be sufficient to unblock.

To prevent similar issues in the future, I'd suggest changing the logic of `modelmapper` so that a warning is produced in case of an "incompatible" java version, instead of throwing an exception.

**Comment by chvid** [comment]
I think the culprit is the use of maven shade to create an "uber" jar. This compiles a particular version of asm into the modelmapper-jar file, making it impossible for users of modelmapper to change the version of asm that is being used (otherwise this would be possible by an explicit dependency on the latest asm and exclusion of the transient dependency.)

**Comment by atelechev** [comment]
> I think the culprit is the use of maven shade to create an "uber" jar.

Yes, this is also important.

I do not know the internals of this project enough and do not know the exact reasons for the choice to package it as an uber-jar, but packaging it as a normal jar without dependencies would also allow to override the dependency that causes the trouble.

**Comment by CynanX** [comment]
The main problem here for me is, does anyone have write access to merge in a pull request and do a release? This repo. looks dead to me, so I'm considering forking or switching to MapStruct.

**Comment by CynanX** [comment]
In terms of changes it's straight forward to update ASM and the shade plugin. Local I've also updated Spring as well.

**Comment by satiamo** [comment]
I need that too please. If it's such a small fix, could you please provide it and release 3.1.2 for java 21?

**Comment by CynanX** [comment]
@alessandro-modolo @chhsiao90

**Comment by dlehammer** [comment]
FYI @jhalterman - a new release with Java 21 support would be much appreciated (~ you're listed as the contact in the [README](https://github.com/modelmapper/modelmapper/blob/eabe6bce51eeb4801cd7f5914315289a3416a5ba/README.md?plain=1#L26)) 🙏

**Comment by jhalterman** [comment]
@CynanX I'm happy to merge a PR and cut a release, if someone wants to create one.

**Comment by CynanX** [comment]
Thank you @jhalterman 

I've created one here, https://github.com/modelmapper/modelmapper/pull/728, thet works when running it locally.

This will force everyone else to also use Java 21 though (it's the future, right?)... so not sure if that is desirable, or perhaps more it to Java 17 at a minimum instead (dictated by Spring support).

**Comment by dlehammer** [comment]
Hi @CynanX,

Regarding
> .. Java 17 at a minimum instead (dictated by Spring support).

I'm already using Java 17 & ModelMapper v3.1.1 without issue, and have for over a year on a large project.
So I'm unsure why this would be an argument against Java 21 support going forward?

> .. dictated by Spring support

Spring 3.2 is slated for Java 21 support, in-order to enable support for [virtual threads](https://spring.io/blog/2023/09/09/all-together-now-spring-boot-3-2-graalvm-native-images-java-21-and-virtual#project-loom) (~ Project Loom) among other things 🤓

**Comment by CynanX** [comment]
Sorry what I meant was, I’ve set the minimum Java version as 21, so if my pull request is merged in then anyone wishing to use it will need to use Java 21 as well.

Is that an issue?

**Comment by dlehammer** [comment]
Hi @CynanX ,

Thanks for elaborating.
It's not an issue for me as I'm aiming for securing Java 21 support in the frameworks that our project depends on, and ModelMapper is one of the frameworks preventing us from upgrading.
I think as long as GH-728 is released as a breaking change (~ major version bump) and reflected in the [changelog](https://github.com/modelmapper/modelmapper/blob/master/CHANGES.md) that should suffice going forward.
(it would still be possible to create patches for 3.x if needed, but I don't see a support schedule for this framework that defines EOL for older releases)

**Comment by CynanX** [comment]
Cool. I've bumped the other dependencies as well, so all being well, hopefully we will have a new version that we can all use soon.

**Comment by chhsiao90** [comment]
Resolved by #729 and will have a release soon.

**Comment by chhsiao90** [comment]
3.2.0 just released, should be available soon on maven central.
