### ISSUE TITLE
Custom mapping in nested objects

### ISSUE THREAD

**Issue by RaulPampliegaMayoral** [modelmapper/modelmapper#727]
Hi all!
I am trying to map a complex, multi-level object like this example:

```java
public class Obj1 {
 private Integer field1;
 private List<Obj2> field2;
}

public class Obj2{
 private Integer field1;
 private Obj3 field2;
}

public class Obj3{
 private Integer field1;
 private String value;
}
``` 
What I am trying to achieve is to set the "field1" property of Obj2 to null and the "value" property of Obj3 to null.

I have tried setting the configuration for different types of objects but with no luck.

```java
modelMapper.typeMap(OtherObj1.class, Obj2.class)....
modelMapper.typeMap(OtherObj2.class, Obj2.class)....
modelMapper.typeMap(OtherObj3.class, Obj3.class)....
``` 

I can process the object once the mapping is done, but I would like ModelMapper to do it, is it possible?

Thanks in advance!

**Comment by CynanX** [comment]
You could always create a converter.

```
public class ExampleConverter extends AbstractConverter<SourceObject, DestinationObject> {

    @Override
    protected DestinationObject convert(SourceObject sourceObject) {
        // code to convert source to destination
    }

}
```

**Comment by RaulPampliegaMayoral** [comment]
Thanks for your response @CynanX 
I have tried to use a Converter to transform from OtherObj1 to Obj1 and the problem I see is that I have to manually define the attributes to map so I would lose the automatic mapping that ModelMapper does.
I understand that to do what I want I would have to define 2 converters (OtherObj2 -> Obj2 and OtherObj3 -> Obj3) and somehow assign these converters to the modelmapper, but don't know how to make this (I tried to do the test in code but nothing functional)

Thanks in advance

**Comment by CynanX** [comment]
You could try creating property maps for each object and then adding the property maps to your model mapper instance instead of converters.

I found this article very helpful: https://www.baeldung.com/java-modelmapper

**Comment by RaulPampliegaMayoral** [comment]
@CynanX 
I finally got it working with a custom Converter for the list of values and applying a mapping with modelMapper

```java
  private static final Converter<List<OtherObj>, List<Obj>> converter = ctx -> {
    if (Objects.isNull(ctx.getSource())) {
      return null;
    }
    return ctx.getSource().stream()
        .map(attr -> modelMapper.map(attr, Obj2.class, CONDITIONAL_KEY))
        .collect(Collectors.toList());
  };

..............................................

    modelMapper.typeMap(OtherObj.class, Obj.class, CONDITIONAL_KEY)
        .setCondition(mapper -> mapper.getTypeMapName().equals(CONDITIONAL_KEY))
        .addMappings(mapper -> mapper
            .using(converter)
            .map(OtherObj::getChildren, Obj::setChildren));
    modelMapper.typeMap(OtherObj2.class, Obj2.class, CONDITIONAL_KEY)
        .setCondition(mapper -> mapper.getTypeMapName().equals(CONDITIONAL_KEY))
        .addMappings(new PropertyMap<OtherObj2, Obj2>() {
          @Override
          protected void configure() {
            skip(destination.getField1());
            skip(destination.getObj3().getField1());
          }
        });
``` 
With this configuration ModelMapper is able to skip the properties so configured.

Thank you very much for your comments and help!
