### ISSUE TITLE
Question regarding configuration setPreferNestedProperties(boolean enabled)

### ISSUE THREAD

**Issue by alfet81** [modelmapper/modelmapper#752]
Hi, I'd like to know a bit more about this configuration option: setPreferNestedProperties(boolean enabled).

The documentation says:

> Sets whether nested properties were preferred when ModelMapper were building the type map with implicit mapping. When true (default), ModelMapper will prefer looking for nested properties for a mapping definition. This option should be disabled when you are trying to map a model contains circular reference.
  modelMapper. createTypeMap(SourceTree. class, DestinationTree. class,
    modelMapper. getConfiguration().copy().setPreferNestedProperties(false));

As I understand from the line above the mapping of circular references should be disabled. Does it still mean that implicit mapping still should work for regular objects with deep level structure or only top level properties will be mapped ignoring the 2, 3, 4, ... level?

**Comment by chhsiao90** [comment]
It should work for deep level structure even with the prefer nested properties was disabled

**Comment by alfet81** [comment]
Thanks for the reply. Yes, I saw this behavior but wasn't sure if that's expected.
