### ISSUE TITLE
Mapping collections using getter.addAll when a setter is not available for the list

### ISSUE THREAD

**Issue by rockamoralesv1** [modelmapper/modelmapper#754]
Hi,

Latest JAXB code generator seems it is not creating a setter for collection types and they suggest to use the getter to get the list and then call the addAll method to mutate the list.

It would be nice if ModelMapper is able to figure out a way to automatically handle the situation for collections, when a field with this type does not have a setter, then use the getter to retrieve the collection and then call addAll method. We could control such a feature using some configuration flag.

does anyone see any issues caused by doing this?

**Comment by chhsiao90** [comment]
I think [Configuration.html#setFieldMatchingEnabled(boolean)](https://modelmapper.org/javadoc/org/modelmapper/config/Configuration.html#setFieldMatchingEnabled(boolean)) and [Configuration.html#setFieldAccessLevel(org.modelmapper.config.Configuration.AccessLevel)](https://modelmapper.org/javadoc/org/modelmapper/config/Configuration.html#setFieldAccessLevel(org.modelmapper.config.Configuration.AccessLevel)) is what you're looking for.

By enabling the field matching, and set the field access level to private, ModelMapper can generate mappings on private fields.

**Comment by rockamoralesv1** [comment]
alright, yes, that should do the work. Thanks
