### ISSUE TITLE
How can I specify the concrete type for java.util.Set?

### ISSUE THREAD

**Issue by xcooper** [modelmapper/modelmapper#89]
# Question

I encounter a problem that I have a DTO must convert to a VO.

```
public class ReportCriteriaDto implements Serializable {
//...
    private Set<ReportOrderDto> reportOrder = new LinkedHashSet<ReportOrderDto>();
//...
}
```

But... after modelmapper.map(), the reportOrder didn't remain in order and I find out that the concrete type of reportOrder becomes java.util.HashSet.

So, I must write a post converter in TypeMap in order to sort the reportOrder.  It's working but not so convenient.

Can ModelMapper fix this in future?

**Comment by skartashov-sandbx** [comment]
Tried to use you solution with `Provider<Set>`, but still have `HashSet`  as destination property.
During debug I found my settings was overridden by `MappingContextHelper` in `CollectionConverter`
Do I need any additional setup?
