### ISSUE TITLE
Mapping from Enum to String - error (Cannot map to final type)

### ISSUE THREAD

**Issue by farrukhmpk** [modelmapper/modelmapper#99]
Hi,
I am trying to map two objects, where the source has an Enum as property and the respective property in destination is of String type. 
The properties are mapped correctly, but I receive (Cannot map to final type) error.
I am using 0.6.3 version of the model mapper. The issue seems to be present in 0.6.4 as well.

As you can see from the code snippet, I have tried using Converter as well, but that didn't help much either.

The relevant code is below.

<pre><code>
public class SourceObject implements Serializable {
    private String name;
    private String description;
    private StatusEnum status;
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }
    public StatusEnum getStatus() {
        return status;
    }
    public void setStatus(StatusEnum status) {
        this.status = status;
    }
}
</code></pre>

<pre><code>
public class DestinationObject implements Serializable {
    private String name;
    private String description;
    private String status;
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }
    public String getStatus() {
        return status;
    }
    public void setStatus(String status) {
        this.status = status;
    }
}
</code></pre>

<pre><code>
public enum StatusEnum {
    INITIATED, SUCCESS, FAILURE;
}
</code></pre>

<pre><code>
public class MessageMapper {
//This is a utility class
    private static ModelMapper mapper = new ModelMapper();
    static {
        try {
            mapper.getConfiguration().setMatchingStrategy(
                    MatchingStrategies.STRICT);

            final Converter&lt;StatusEnum, String&gt; converter = new AbstractConverter&lt;StatusEnum, String&gt;() {
                @Override
                protected String convert(StatusEnum s) {
                    return s.name();
                }
            };

            mapper.addMappings(new PropertyMap&lt;SourceObject, DestinationObject&gt;() {
                @Override
                protected void configure() {
                    // using(converter).map().setStatus(source.getStatus().name());
                    map().setStatus(source.getStatus().name());
                }
            });

        } catch (Throwable t) {
            t.printStackTrace();
        }
    }

    public static ModelMapper getMapper() {
        return mapper;
    }

    public static &lt;T&gt; T translate(Object source, Class&lt;T&gt; target) {
        return mapper.map(source, target);
    }

}
</code></pre>

<pre><code>
public class ModelMappingTester {
    public static void main(String[] args) {
        SourceObject src = getSourceObject();
        DestinationObject dest = MessageMapper.translate(src,
                DestinationObject.class);

        System.out.println("name: " + dest.getName());
        System.out.println("description: " + dest.getDescription());
        System.out.println("status: " + dest.getStatus());
    }

    private static SourceObject getSourceObject() {
        SourceObject src = new SourceObject();
        src.setName("John Doe");
        src.setDescription("John Doe is an analyst.");
        src.setStatus(StatusEnum.SUCCESS);

        return src;
    }
}
</code></pre>

The error is as follows:

<pre><code>
org.modelmapper.ConfigurationException: ModelMapper configuration errors:

1) Cannot map to final type.

1 error
    at org.modelmapper.internal.Errors.throwConfigurationExceptionIfErrorsExist(Errors.java:239)
    at org.modelmapper.internal.ExplicitMappingBuilder.build(ExplicitMappingBuilder.java:176)
    at org.modelmapper.internal.TypeMapImpl.addMappings(TypeMapImpl.java:72)
    at org.modelmapper.internal.TypeMapStore.getOrCreate(TypeMapStore.java:101)
    at org.modelmapper.ModelMapper.addMappings(ModelMapper.java:93)
</code></pre>

Any help will be greatly appreciated.

**Comment by mystarrocks** [comment]
I have a similar problem where the source type in my case in an enum called `Status` and the target type is an `Integer` that can be obtained by calling `Status.code()`. Is there any way to get it work in my case? I don't see either of these `addMappings` would working:

```
map(source.getStatus().code()).setStatus(null);
```


```
map().setStatus(source.getStatuts().code());
```

**Comment by beiyeren** [comment]
map(source.getStatus()).setStatus(null);  not work

how can i fix it?

**Comment by rhuankarlus** [comment]
I have the same problem described here.
Why is this issue closed?

MM version: 0.7.5

**Comment by alexspring123** [comment]
I have the same problem，who fix it？

**Comment by rajeshmepco** [comment]
I too have the same problem. Is there any solution to this?

**Comment by psamwel** [comment]
Only way I could get around it in my scenario was to create a Converter<EnumSourceType, EnumDestType> like:

`    public static Converter<EnumSourceType, EnumDestType> enumConverter = new Converter<EnumSourceType, EnumDestType>()
    {
        @Override
        public EnumDestType convert(MappingContext<EnumSourceType, EnumDestType> mappingContext) {
            if(mappingContext.getSource() != null) {
                return EnumDestType.valueOf(mappingContext.getSource().toString());
            }
            return null;
        }
    };`

And then specify the conversion in the PropertyMap<SourceObject, DestObject> as:
`using(enumConverter).map().setVendorStatus(this.<EnumDestType>source("getStatus"));`

**Comment by javeednawab** [comment]
I am facing this issue even for mismatch types , no matter how I configure mappings I end up getting same exception 

> Cannot map to final type     ***Builder 

I see that in the the generated model of my pojo builders are marked as final .

```
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.infinera.nm.ni.inventory.Xcon)
      com.xxx.xx.xx..XXOrBuilder { 
```
pom.xml for codegen of proto files

`
<build>
        <extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.6.2</version>
            </extension>
        </extensions>
        <plugins>
            <plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
`

how I do mismatch configuration

`
TypeMap<Src, DestProto.Builder> builderTypeMap
                = mapper.createTypeMap(Src.class,  DestProto.Builder.class);
        chassisBuilderTypeMap.addMappings(map -> map.map(Src::getATTr,  DestProto.Builder::setMisMatchAttrType));
`

**Comment by rana2884** [comment]
This worked for me
` PropertyMap<Staff, StaffDto> staffMap =
            new PropertyMap<>() {
                protected void configure() {
                    using(enumConverter).map(source.getStatus()).setStatus(null);
                }
            };

    Converter<Status, String> enumConverter =
            ctx -> ctx.getSource() == null ? null : ctx.getSource().getName();`

**Comment by AloisSeckar** [comment]
Sorry for doing necromancy here, but I am facing quite the same issue. Thanks to comments here I managed to get my bundle up and running, but I think I need a little explanation:

`using(enumConverter).map(source.getStatus()).setStatus(null);`

With this line of code I will end up with `status` being actually mapped to the correct incomming value? If yes, why? Or will it be `null` and this is just to overcome the mapping error?

**Comment by dlehammer** [comment]
Hi @AloisSeckar,

> With this line of code I will end up with `status` being actually mapped to the correct incomming value?

Correct, as the `enumConverter` will be invoked with the `source.getStatus()` value as input and the ModelMapper will apply the output to the `target.setStatus(<output>)`.

> If yes, why? Or will it be `null` and this is just to overcome the mapping error?

As setters, like the `setStatus(Status status)`, has a method signature with an argument - the Java compiler requires an argument at compile time.
The `null` is overridden runtime by the ModelMapper 🤓 

(this "final type" issue is similar to #391 )
